### ISSUE TITLE
Cant seem to place an options order

### ISSUE THREAD

**Issue by LonginusHeart** [areed1192/td-ameritrade-python-api#10]
First of all thank you for picking up where the Ameritrade API leaves off and making this awesome repo.
Second off I'm trying to place an order and it just won't take. Can you look at my order process and let me know if I'm missing anything? I'm using MATLAB to call python so some of the commands look a little funny, but I've done it before and I don't think it's the problem. Ty

Csymbol = 'MSFT_031320C155';
new_order = py.td.orders.Order();
new_order.order_session(pyargs('session', 'NORMAL'));
new_order.order_duration(pyargs('duration','GOOD_TILL_CANCEL'));
new_order.order_type(pyargs('order_type', 'MARKET'));
new_order_leg = py.td.orders.OrderLeg();
new_order_leg.order_leg_instruction(pyargs('instruction','BUY_TO_OPEN'));
quant = py.int(1);
new_order_leg.order_leg_quantity(pyargs('quantity',quant));
new_order_leg.order_leg_asset(pyargs('asset_type','OPTION','symbol',Csymbol));
new_order.add_order_leg(pyargs('order_leg',new_order_leg));
TDSession.place_order(pyargs('account',myaccountid, 'order', new_order));

**Comment by LonginusHeart** [comment]
I'm getting this error dialogue:
'A validation error occurred while processing the request.'

**Comment by areed1192** [comment]
I know this is old, but I wanted to address it just in case anyone else has this issue. When you're building the order, there are a couple of things that seem to be causing the problem.

1. The Order Type can't be `MARKET`; it needs to be a `LIMIT` order type. At least from what I can tell right now.
2. You need to add the `orderStrategyType` argument. In this case, `SINGLE` should be okay.
3. Because you need to use a limit price, you'll need to add another argument, `price`.

Here is what the JSON would look like, keep in mind the price is fake.

```json
{
    "session": "NORMAL",
    "duration": "GOOD_TILL_CANCEL",
    "orderStrategyType": "SINGLE",
    "orderType": "LIMIT",
    "price": 12.00,
    "orderLegCollection": [
        {
            "instruction": "BUY_TO_OPEN",
            "quantity": 1,
            "instrument": {
                "assetType": "OPTION",
                "symbol": "MSFT_032020C115"
            }
        }
    ]
}
```

Here is the Python code:

```python
# Create the Order.
option_order = Order()
option_order.order_session(session = 'NORMAL')
option_order.order_duration(duration = 'GOOD_TILL_CANCEL')
option_order.order_type(order_type = 'LIMIT')
option_order.order_strategy_type(order_strategy_type = 'SINGLE')
option_order.order_price(price = 12.00)

# Create the Order Leg
option_order_leg = OrderLeg()
option_order_leg.order_leg_instruction(instruction = 'BUY_TO_OPEN')
option_order_leg.order_leg_quantity(quantity = int(1))
option_order_leg.order_leg_asset(asset_type = 'OPTION', symbol = 'MSFT_032020C115')

# Add the Order Leg to the Order
option_order.add_order_leg(order_leg = option_order_leg)
```

Let me know if this fixes the issue.

**Comment by LonginusHeart** [comment]
Thank you for the in-depth reply. I've run your exact code in a proper
python environment and it's still giving me the validation error. I also
tried a different symbol but no luck. Since I can successfully pull my
order status on the account, I figure that means it's either 1) an account
issue- so I reached out to the TD folks directly- or 2) an issue with how
I'm running my other bits of code, above and below your code example.

Upstream I have:

# Create a new session
TDSession = TDClient(account_number=ACCOUNT_NUMBER,
                     account_password=ACCOUNT_PASSWORD,
                     consumer_id=CONSUMER_ID,
                     redirect_uri=REDIRECT_URI)

# Login to the session
TDSession.login()


and downstream I have:

TDSession.place_order(account=ACCOUNT_NUMBER, order=option_order)


I notice I never use my ACCOUNT_USERNAME variable. Could that have
something to do with it? Or is it interchangeable with the
ACCOUNT_NUMBER?


Thanks again

-Ross

**Comment by areed1192** [comment]
I made some changes yesterday to the TD Library and pushed through those updates. With that being said, I would first make sure that you update the library to the following version:

```python
pip install td-ameritrade-python-api==0.2.2
```

After doing that, try your code again and see if that fixes it. Regarding the `ACCOUNT_NUMBER` you have it correct, the argument you should pass through to:

```python
TDSession.place_order(account = account_number, order = option_order)
```

is the account number you want to place the trade for.

**Comment by LonginusHeart** [comment]
I think that did it! I'll give it a spin for serious on Monday. Thank you
for this. For real.
=)

**Comment by areed1192** [comment]
Awesome, glad that fixed it! Since you seem to be in a good spot, I'm going to close the issue now.
