### ISSUE TITLE
Websocket error cod 1006

### ISSUE THREAD

**Issue by comlong** [areed1192/td-ameritrade-python-api#100]
Everyday, I use the stream to record data from the TD server. Recently, I got this error several times. And the error happens always on 7AM Eastern Time (ET).

websockets error :  code = 1006 (connection closed abnormally [internal]), no reason
Connection with server closed, beginning close process...at time :  2020-09-02 07:00:04.453874

Does someone know why and how to fix it?
Thanks

**Comment by areed1192** [comment]
It sounds like it's on TD's end, they might be doing something to their server. Also, keep in mind, that the stream works very differently in pre-market hours than during regular market hours.
