### ISSUE TITLE
Is TDClient multi-thread safe?

### ISSUE THREAD

**Issue by xuewei4d** [areed1192/td-ameritrade-python-api#101]
Hi,

First, thanks for creating this awesome python package.

I'm trying to run multi-threads to get the option data on a daily basis.  I'm wondering if TDClient is thread-safe? 

Thanks!
W

**Comment by areed1192** [comment]
At this point, I would say no because you could have issues when it comes to refreshing the token. You could run into a situation where they could conflict with each other. Regardless, you would be limited to 500 symbols because of the constraints TD sets into place.

**Comment by xuewei4d** [comment]
Thanks
