### ISSUE TITLE
Streaming API - TypeError: argument of type 'NoneType' is not iterable 

### ISSUE THREAD

**Issue by joeltok** [areed1192/td-ameritrade-python-api#107]
Thanks for the great work, this library is looking wonderful for the REST APIs. For streaming however, I am running into a hiccup.

Running the [sample script for the streaming api](https://github.com/areed1192/td-ameritrade-python-api/blob/d0c611f73b6e60df669f15536244e4fd9e7fee6f/samples/api_pipeline.py) I encounter the error: _TypeError: argument of type 'NoneType' is not iterable_ at [line 69](https://github.com/areed1192/td-ameritrade-python-api/blob/d0c611f73b6e60df669f15536244e4fd9e7fee6f/samples/api_pipeline.py#L69).

Any clue what might be causing this?

**Comment by areed1192** [comment]
Could you provide some more details on this? When you run it is it during certain times of the day you experience this issue? Right now, I'm not experiencing it, so I'm not sure what it could be. Also, are you on Mac or Windows?

**Comment by joeltok** [comment]
Hey thanks for the reply. I'm running the code from Ubuntu. 

I suspect this had something to do with realtime permissions, but anyway I decided to switch to polling with the REST API instead, so am not using this any longer.
