### ISSUE TITLE
Place order to purchase a fix amount of dollar worth of options with TD API

### ISSUE THREAD

**Issue by andymingxinsun** [areed1192/td-ameritrade-python-api#108]
Hi Alex,

For example, in ThinkorSwim, i can submit an order to buy 10 option contracts at a limited price per contract. It also allows me to buy $500 dollar worth of option contracts at a limited price per contract. I know the TD API allow the first approach with no problem. But does it support the second approach? If so, would you share the JSON request detail for the second approach? Many thanks

Andy

**Comment by areed1192** [comment]
So, this is one I can only speak of one person who tried this and we both were unsuccessfully able to do option number 2. It doesn't appear you can send the TD API a dollar amount to purchase. Now there is an extremely easy workaround for this, simply pull the real-time quote and calculate it yourself. It's an extra step, but I think it'll be the path of least resistance.

**Comment by eyesuk** [comment]
👍🏾👍🏾

**Comment by andymingxinsun** [comment]
Hi Alex,

Thank you for getting back to me. My application is currently doing what
you suggested. However, it will take 2 webservice calls (one to get a
quote, another one to submit an order) to get an order submitted. I was
trying to see if there is a way to do it in one call.
I also reached out to the TD DEV team about this. They confirmed that their
current API does not support option #2. ToS does support option #2.It does
the calculation internally.

Another quick question about your API, I see the TDStreamerClient current
save data into CSV files. Is there any planning to add a function to insert
data into a DB in the future? or is it expected to handle on application
side?

Again, I want to thank you for your time and effort to create this API for
all of us. Many thanks.

Andy
