### ISSUE TITLE
Sending EXT orders for Extended Hours Trading

### ISSUE THREAD

**Issue by ahmetsbilgin** [areed1192/td-ameritrade-python-api#111]
Hello,

Sending 'EXT' orders is not possible as far as I can see. Is there a workaround for that?

I have checked the TDA API documentation and there is no option to send 'EXT' orders under "duration".

Anyone tried to send such orders, your help is much appreciated.

**Comment by areed1192** [comment]
It's because you need to use different arguments for the session. Here are the options.

```json
"session": 'NORMAL'
"session": 'AM'
"session": 'PM'
"session": 'SEAMLESS'
```

**Comment by ahmetsbilgin** [comment]
Thank you, a LIMIT order for the AM session should work then.
