### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Dhammer3** [areed1192/td-ameritrade-python-api#112]
Do you think that this project could benefit from some refactoring? some of the code has several layers of nesting. There are quite a few lines with comments describing the behavior of the block. Would some of this read a little better/reduce cognitive load if they were moved into functions or refactored a bit? Maybe not the highest priority at the moment, but If you think this is a good idea I would be happy to help! @areed1192

**Comment by areed1192** [comment]
I'm always open to people adding enhancements or just trying to improve the overall code, so if you have suggestions, I'm all open to seeing them. **:)**
