### ISSUE TITLE
Stop limit order for option spread

### ISSUE THREAD

**Issue by hnguyen2k** [areed1192/td-ameritrade-python-api#113]
Hi,

I've been trying to set a stop limit order for a vertical spread, but haven't been successful.

Whenever I set the order_type to ORDER_TYPE.STOP_LIMIT, I got the following error from the broker:
_"OrderType must be one of those values: NET_CREDIT, NET_DEBIT, NET_ZERO or MARKET."_

If I set the orderType to OrderType.NET_CREDIT or OrderType.NET_DEBIT, it became a Limit Order, which is not a Stop Limit Order.

Here is my code to build a stop limit order to buy back a vertical spread:

```
def get_vertical_spread_stop_limit_order(
            sell_symbol, buy_symbol, quantity, stop_price, limit_price):

        new_order = Order()
        new_order.order_session(ORDER_SESSION.NORMAL)
        new_order.order_duration(DURATION.DAY)
        new_order.order_type(ORDER_TYPE.NET_DEBIT)
        new_order.order_strategy_type(ORDER_STRATEGY_TYPE.SINGLE)
        new_order.complex_order_type(COMPLEX_ORDER_STRATEGY_TYPE.VERTICAL)

        new_order.stop_type(STOP_TYPE.BID)
        new_order.stop_price(stop_price)
        new_order.order_price(limit_price)

        _sell_order_leg = OrderLeg()
        _sell_order_leg.order_leg_instruction(ORDER_INSTRUCTIONS.SELL_TO_CLOSE)
        _sell_order_leg.order_leg_quantity(quantity)
        _sell_order_leg.order_leg_asset(asset_type=ORDER_ASSET_TYPE.OPTION, symbol=sell_symbol)
        new_order.add_order_leg(_sell_order_leg)

        _buy_order_leg = OrderLeg()
        _buy_order_leg.order_leg_instruction(ORDER_INSTRUCTIONS.BUY_TO_CLOSE)
        _buy_order_leg.order_leg_quantity(quantity)
        _buy_order_leg.order_leg_asset(asset_type=ORDER_ASSET_TYPE.OPTION, symbol=buy_symbol)
        new_order.add_order_leg(_buy_order_leg)

        return new_order
```

Even when I set a stop price with NET_DEBIT, I got another error from the server:
 _"Stop price must be populated only for stop orders."_

I am unable to figure out what the problem is. Does anyone know what wrong with the code or is it a limitation from TD API on creating a stop limit order for an option spread? Do you have any working sample code/json? Thanks!

**Comment by areed1192** [comment]
So, don't take my word on this, but I believe TD has changed some of its complex strategies. I had someone reach out a few months ago when they were trying to do a Butterfly Strategy and TD, I guess is removing that from the API. I would not be surprised if they are doing that with the other complex strategies.
