### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by richdevboston** [areed1192/td-ameritrade-python-api#118]
The installation using `# pip install td-ameritrade-python-api` or  `pip install --upgrade td-ameritrade-python-api` both fail with the following error:

ERROR: Could not find a version that satisfies the requirement td-ameritrade-python-api (from versions: none)
ERROR: No matching distribution found for td-ameritrade-python-api

This was caused because I was using a conda environment with a Python 3.6 runtime kernel.  
Once I changed to (activated) another environment with a Python 3.7 kernel, the `import`  statement worked fine.

**Comment by areed1192** [comment]
Yes, the library is only compatible with python 3.7 or greater.
