### ISSUE TITLE
Don't quietly store my credentials without me knowing

### ISSUE THREAD

**Issue by helgridly** [areed1192/td-ameritrade-python-api#119]
I just started using this library and logged in without passing `credentials_path` to the `TDClient` constructor. I then reran it and it didn't ask me to log in a second time.

After a bit of digging I discovered that if no credentials_path is specified you pick the site-packages directory and save `td_state.json` there. As a user, I don't want extremely powerful credentials to all my finances left in odd places around my computer without me knowing. My expectation is that if I don't pass a `credentials_path`, I'll have to log in manually every time.

I understand that this is meant to be a convenience function but from my perspective this is a security risk. I had _no idea_ where this application was storing my credentials and totally freaked out. (As an aside, a module's site-packages directory is a really weird place to store state.)

I strongly suggest you remove the credential file auto-creation feature, let the user optionally pass in a file path, and store the credentials there if they did. At the very least you should document in the usage section that the library will save off your credentials, and where.

(Same goes for settings - they shouldn't just be tucked away in a hidden folder in my home directory without you saying so.)

**Comment by areed1192** [comment]
This has been removed in the latest update, you now must specify where you want to cache your token. This was previously brought up and I decided to remove it since the convenience didn't warrant it.

**Comment by CalamariAce** [comment]
@areed1192 Please consider updating the "Usage" section in client.py to match your changes. It threw me for a loop trying to make something work which is no longer allowed :)

**Comment by areed1192** [comment]
The usage was updated, and the credentials path check was added but aren't in the release yet.
