### ISSUE TITLE
Streaming issues: local variables and message formatting

### ISSUE THREAD

**Issue by MattsonThieme** [areed1192/td-ameritrade-python-api#12]
Hello, I'm using the `test_streaming_client.py` as a template, and getting a few errors. To start off, here is my code (I'm using v0.2.2):

```
import requests
from td.client import TDClient
import config

# Create a new session
TDSession = TDClient(account_number = config.account_number,
                     account_password = config.account_password,
                     consumer_id = config.consumer_id,
                     redirect_uri = config.redirect_uri)

# Login to the session
TDSession.login()
# Create a streaming sesion
TDStreamingClient = TDSession.create_streaming_session()
# Define the CSV Append Mode. Needs to be rewritten it's kind of awkward to call it like this.
TDStreamingClient.CSV_APPEND_MODE = True
# Actives
TDStreamingClient.actives(service='ACTIVES_NASDAQ', venue='NASDAQ', duration='ALL')
# Quality of Service
TDStreamingClient.quality_of_service(qos_level='express')
# Level One Quote
TDStreamingClient.level_one_quotes(symbols=["VOO"],  fields=list(range(0,8)))
# Stream it.
TDStreamingClient.stream()
```

And I'm getting the following error:

```
Traceback (most recent call last):
  File "streaming.py", line 92, in <module>
    TDStreamingClient.quality_of_service(qos_level='express')
  File "/Users/mattsonthieme/miniconda3/envs/tdameritrade/lib/python3.7/site-packages/td/stream.py", line 427, in quality_of_service
    qos_level = self._validate_argument(argument=qos_level, endpoint='qos_request')
  File "/Users/mattsonthieme/miniconda3/envs/tdameritrade/lib/python3.7/site-packages/td/stream.py", line 412, in _validate_argument
    arg_list.append(key_value)
UnboundLocalError: local variable 'arg_list' referenced before assignment
```

It appears that `arg_list` is defined in the if block on line 386 of `td/stream.py` and not visible in the else block. Moving the arg_list initialization outside the if statement to line 381 fixes the UnboundLocalError issue but then produces another. It looks like the formatting of the messages (at least for `level_one_quotes`) may be a bit off, as I get the following error:

```
Connection established. Streaming will begin shortly.
--------------------
Received message from server: {'response': [{'service': 'ADMIN', 'requestid': '0', 'command': 'LOGIN', 'timestamp': 1584972659701, 'content': {'code': 0, 'msg': '02-2'}}]}
--------------------
Received message from server: {'response': [{'service': 'ADMIN', 'requestid': '0', 'command': 'LOGOUT', 'timestamp': 1584972659701, 'content': {'code': 21, 'msg': 'Bad command formatting'}}]}
Connection with server closed
```

I'm reading TDA's docs online but not sure exactly what about the request is incorrect.

**Comment by MattsonThieme** [comment]
Interesting. As a test, I commented out the `quality_of_service` line in the code above and am now getting the following error:

```
Connection established. Streaming will begin shortly.
--------------------
Received message from server: {'response': [{'service': 'ACTIVES_NASDAQ', 'requestid': '1', 'command': 'SUBS', 'timestamp': 1584974506682, 'content': {'code': 20, 'msg': 'STREAM CONNECTION NOT FOUND - Please login again.'}}]}
--------------------
Received message from server: {'response': [{'service': 'ADMIN', 'requestid': '0', 'command': 'LOGIN', 'timestamp': 1584974506682, 'content': {'code': 0, 'msg': '03-2'}}]}
Connection with server closed
```

Do we need to login again, or in another way (other than `TDSession.login()`), when we initialize a streaming client?

**Comment by areed1192** [comment]
I fixed the `quality_of_service` endpoint so that shouldn't be an issue. However, the second issue I haven't been able to recreate. What exactly happens to cause that?

**Comment by hrdymchl** [comment]
@areed1192, thanks so much for sharing your work! I am attempting the same thing as @MattsonThieme and also faced the same initial issue as him

I've pulled your latest commits and am running `test_streaming_client.py` with my personal credentials but it throws, `AttributeError: 'TDStreamerClient' object has no attribute 'write_behavior'`

**Comment by areed1192** [comment]
you need to update the library to the latest version I just uploaded it to PyPi so you should have access to that method now

**Comment by MattsonThieme** [comment]
@areed1192 I'm not sure exactly what causes it, because the first thing I get back is `Connection Established`, so I'm not sure at what point we're getting disconnected.

Running the same code with the new 0.2.3 yields the following error:

```
Connection established. Streaming will begin shortly.
--------------------
Received message from server: {'response': [{'service': 'QUOTE', 'requestid': '3', 'command': 'SUBS', 'timestamp': 1586102083406, 'content': {'code': 3, 'msg': 'Login Denied. - Please login first.'}}]}
--------------------
Received message from server: {'response': [{'service': 'ADMIN', 'requestid': '0', 'command': 'LOGIN', 'timestamp': 1586102083406, 'content': {'code': 0, 'msg': '01-3'}}]}
Connection with server closed
```

With the error `'Login Denied. - Please login first.'`, it looks like it wants me to login again, but I'm not sure where or how I should go about that, as I login immediately after creating the client object and have no issue grabbing regular quotes with that logged-in client.

**Comment by areed1192** [comment]
@MattsonThieme I think I found the issue with the login, in some cases, the login happens after sending the first service request which then fails because the login never took place. I have a possible workaround that I'm going to try and implement in the library to hopefully fix the main issue. In short, we are going to add a short pause in the script to give it time to log in.

I'm going to keep this open until that is resolved.

**Comment by areed1192** [comment]
Closing this out, since the bug was resolved in the latest version. For more info on the changes please refer to issue #29
