### ISSUE TITLE
invalid_grant error, refresh token issue

### ISSUE THREAD

**Issue by guohuang** [areed1192/td-ameritrade-python-api#124]
I generated a creds file and run my script for 30 minutes. after that i get a 400 errors
```
RESPONSE TEXT: {
  "error" : "invalid_grant"
}
```

anyone has this issue? this error is intermittent, sometimes it runs longer than 30 minutes. according to the doc, the creds file should run for at least 90 days

**Comment by csreyes** [comment]
same issue here. i'm using localhost as my redirect_uri...is that an issue ?

**Comment by areed1192** [comment]
Hey, @guohuang and @csreyes  if you could please clone the repo to grab the latest updates I made. I plan to do another release later this week, but I want to make sure they address the issue.

**Comment by csreyes** [comment]
awesome. thanks @areed1192 !

**Comment by areed1192** [comment]
@csreyes Was the latest update able to resolve your issue?

**Comment by csreyes** [comment]
i think i ran into some caching issues with my existing state file. I had issues getting into a fresh state with the update, so reverted the version to recreate the state file. after updating the package, things have been running smoothly. appreciate the update
