### ISSUE TITLE
Futures data not being returned

### ISSUE THREAD

**Issue by ElliotVilhelm** [areed1192/td-ameritrade-python-api#126]
```
data = session.get_price_history(
        symbol='/ES',
        period_type='day',
        period=5,
        frequency_type='minute',
        frequency=1
    )
```

does not return futures data but actual "$ES" data

![image](https://user-images.githubusercontent.com/22024236/99893345-acdc3900-2c33-11eb-8c89-28cba302dce8.png)

**Comment by ElliotVilhelm** [comment]
Ok I dont think td api even supports historical futures data

**Comment by areed1192** [comment]
Sadly no, the documentation on TD is misleading they say you can but unfortunately when we reached out the feature isn't there.

**Comment by ElliotVilhelm** [comment]
Thanks, closing issue.
