### ISSUE TITLE
Install from Dockerfile, have error

### ISSUE THREAD

**Issue by kooyear** [areed1192/td-ameritrade-python-api#129]
ERROR: Could not find a version that satisfies the requirement td-ameritrade-python-api==0.3.1 (from -r /auto-trade/requirements.txt (line 26)) (from versions: none)
ERROR: No matching distribution found for td-ameritrade-python-api==0.3.1 (from -r /auto-trade/requirements.txt (line 26))

**Comment by areed1192** [comment]
What version of python are you using? It's compatible with 3.7 and above.
