### ISSUE TITLE
Can't paste in URL redirect to terminal (length cutoff?)

### ISSUE THREAD

**Issue by davemw15** [areed1192/td-ameritrade-python-api#130]
When I try to paste in the full RUL redirect the last 11 digits. I'm wondering whether there is some sort of length limit coded in that might be too short? Or maybe the nature of the issue is different.

**Comment by davemw15** [comment]
I haven't looked in the code to check why this is happening. It's possible that it's related to my terminal, but I have tried it with both iTerm and Alacritty, so maybe that's not it. If anyone has this issue, if you put a breakpoint in your code with pdb (or any other debugger probably), you can work around this.

**Comment by areed1192** [comment]
It's a mac specific error unfortunately, the terminal cuts it off after a certain length. The easiest way around it is to just run through the process a few times and wait till you get a code that is less than the maximum character the terminal can handle.
