### ISSUE TITLE
Latest update breaks authentication

### ISSUE THREAD

**Issue by ElliotVilhelm** [areed1192/td-ameritrade-python-api#134]
## System
```
td-ameritrade-python-api 0.3.2
Python 3.8.5
```

## Script
```
import time
from td.client import TDClient

TDSession = TDClient(
    client_id='xx',
    redirect_uri='http://localhost',
    credentials_path='/home/ubuntu/credentials.json'
)


TDSession.login()
data = TDSession.get_price_history(
    symbol='SPY',
    period_type='day',
    period=10,
    frequency_type='minute',
    frequency=10,
    end_date=int(round(time.time() * 1000))
)

print(data)
```
## Output
```
Grabbing new refresh token...
Grabbing new access token...
Grabbing new refresh token...
Grabbing new access token...
Traceback (most recent call last):
  File "test_td.py", line 13, in <module>
    data = TDSession.get_price_history(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/td/client.py", line 802, in get_price_history
    return self._make_request(method='get', endpoint=endpoint, params=params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/td/client.py", line 606, in _make_request
    raise TknExpError(message=response.text)
td.exceptions.TknExpError: {"error":"Not Authorized."}
```

```
TDSession = TDClient(
    client_id='x',
    redirect_uri='http://localhost',
    credentials_path='/home/ubuntu/credentials.json'
)
```

I do not see `credentials.json` being generated at all.

My thought is there is some caching occurring between version update, even with a pip uninstall and a reinstall of the new version I am not prompted to paste in a new redirect URL.

I removed the update using 
```
pip3 uninstall td-ameritrade-python-api
pip3 install td-ameritrade-python-api==0.3.1
```
and was prompted to redo the redirect URL auth. Something broken here.

**Comment by areed1192** [comment]
Have you tried just deleting the `credentials.json` file entirely? That usually prompts you to go to the URL.

**Comment by ElliotVilhelm** [comment]
`credentials.json` is never generated

**Comment by cvartanian** [comment]
I'm also experiencing this issue across multiple machines :(

**Comment by areed1192** [comment]
@cvartanian Do any errors appear when you run the code?

@ElliotVilhelm Can I ask you to clone the latest push I made to the repo? I've pushed a few changes today and I want to see if any of them fix your issue. More importantly, let me know if you see any output or encounter any errors. I want to see if it has something to do with your file path that my code isn't capturing or if it's a bug on my end.

**Comment by ElliotVilhelm** [comment]
Can confirm the latest version of master does not have this issue and is working well with `credentials_path` @areed1192

**Comment by areed1192** [comment]
@ElliotVilhelm Awesome, that's a good sign. I'm going to see if more people have their issue resolved and if so, I'll do the next release.

**Comment by paulmure** [comment]
I have a similar issue.

I tried to run this script for the first time
`from td.client import TDClient
from config import CONSUMER_KEY, REDIRECT_URI, JSON_PATH


td_client = TDClient(client_id=CONSUMER_KEY, redirect_uri=REDIRECT_URI, credentials_path=JSON_PATH)

td_client.login()
`
Which gave me this error
`Traceback (most recent call last):
  File ".\td_trader.py", line 7, in <module>
    td_client.login()
  File "C:\ProgramData\Anaconda3\lib\site-packages\td\client.py", line 241, in login
    if self._silent_sso():
  File "C:\ProgramData\Anaconda3\lib\site-packages\td\client.py", line 467, in _silent_sso
    if self.validate_token():
  File "C:\ProgramData\Anaconda3\lib\site-packages\td\client.py", line 435, in validate_token
    refresh_token_exp_threshold = refresh_token_exp_threshold.timestamp()
OSError: [Errno 22] Invalid argument`

I commented out the block of code that checks if the token is expired in client.py, which made this error go away, but the script just seems to do nothing.

My system:

td-ameritrade-python-api 0.3.2
Python 3.8.5
Windows 10 Version 20H2

**Comment by paulmure** [comment]
Update

I changed the validate_token method in client.py so it always return False. Now I am able to get to the authentication step, but after pasting in the the full URL redirect, I got this error

```
Traceback (most recent call last):
  File ".\td_trader.py", line 7, in <module>
    td_client.login()
  File "C:\ProgramData\Anaconda3\lib\site-packages\td\client.py", line 245, in login
    self.oauth()
  File "C:\ProgramData\Anaconda3\lib\site-packages\td\client.py", line 361, in oauth
    self.exchange_code_for_token(
  File "C:\ProgramData\Anaconda3\lib\site-packages\td\client.py", line 384, in exchange_code_for_token
    url_code = list(url_dict.values())[0][0]
IndexError: list index out of range
```

**Comment by areed1192** [comment]
@paulmure Are you using the library on PyPi or the repo version? If you're not using the repo version can you clone it and see if you still encounter the same issue?

**Comment by goarmy0101n** [comment]
@paulmure I believe this is an issue with the datetime object refresh_token_exp_threshold and access_token_exp_threshold in the validate_token method of client.py.  I changed the "Convert to Seconds" part to this:

` 
# Convert to Seconds.       
epochdate = datetime.datetime(1970,1,1)
refresh_token_exp_threshold = (refresh_token_exp_threshold-epochdate).total_seconds()
access_token_exp_threshold = (access_token_exp_threshold-epochdate).total_seconds()
`

**Comment by paulmure** [comment]
@areed1192 I was using the PyPi library. I cloned the repo version and it's working correctly.

@goarmy0101n I tried your solution, the original problem was gone, but it still doesn't seem to be starting the authentication process.

```
Grabbing new refresh token...
Grabbing new access token...
Grabbing new refresh token...
Grabbing new access token...
Traceback (most recent call last):
  File ".\td_trader.py", line 9, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\td\client.py", line 736, in get_quotes
    return self._make_request(method='get', endpoint=endpoint, params=params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\td\client.py", line 610, in _make_request
    raise TknExpError(message=response.text)
td.exceptions.TknExpError: {"error":"Not Authorized."}
```
But the repo version is working correctly though.

**Comment by msingh00** [comment]
im having the same issue w/ the pypi version as well

**Comment by goarmy0101n** [comment]
@paulmure I also run into that issue.  This is after I've logged in successfully and gone through the process of pasting the redirect path and storing the state file.  This is what happens when I try out the sample get_quotes call:
```
msft_quotes = TDSession.get_quotes(instruments=['MSFT'])
Grabbing new refresh token...
Grabbing new access token...
TknExpError: {"error":"Not Authorized."}
```

Taking a deeper look, the state seems to reset itself to defaults, with access_token_expires_at = 0  and refresh_token_expires_at = 0, even though the state file exists with correct information.

**Comment by areed1192** [comment]
The update was pushed out, closing the thread.
