### ISSUE TITLE
Login process: how do I get consumer_id and redirect_uri ?

### ISSUE THREAD

**Issue by reikred** [areed1192/td-ameritrade-python-api#14]
I don't understand the login process. I used the example script from README.md, and filled in 
account_number and account_password for my ameritrade account, but I apparently I do not understand where consumer_id and redirect_uri are supposed to come from.

First, if I run the script with just the dummy values for consumer_id and redirect_uri, the script produces a a redirect_url that includes said dummy values and the browser (after pasting that URL) just says

_A third-party application may be attempting to make unauthorized access to your account. For help with your account, contact us. For information on securing your account, visit the TD Ameritrade Security page._ (*)

Second, if I try instead to generate an Oauth recipe at 
https://developer.tdameritrade.com/account-access/apis/get/accounts/%7BaccountId%7D-0
then I get a login window pop-up, and can login and run commands on the webpage. But again I do not understand how I should set the consumer_id and redirect_uri variables from the OAuth "curl" values.  I made some GUESS about this but when I plug the values into the script all I get when running is the same error message above (*).

I realize this must be a dumb question but I simply do not understand the logic of the recipe. Can you please help? I need to understand both consumer_id and redirect_uri, please.

**Comment by reikred** [comment]
I note that README.md mentions nothing about having to register an "app" with tdameritrade, but that this is in fact necessary. There should be some explanation added into the Documentation and Resources section of README.md, saying that you have to follow those instructions o regioster an app before proceeding.

I'm still trying to work out the details, so please leave this issue open.

**Comment by macevhicz** [comment]
I am also in process of learning to do this. So far, here's what to do... There are somewhat cryptic instructions here: https://developer.tdameritrade.com/content/getting-started and here: https://developer.tdameritrade.com/content/simple-auth-local-apps

1) Must have a TDAmeritrade account
2) Create a TDAmeritrade developer account also: https://developer.tdameritrade.com/
3) Once you have that, create an App within TDAmeritrade developer site, under MyApps.
- You provide the redirectURI, for general use, 'https://127.0.0.1' which is the localhost
- It will generate the Consumer ID
4) Note that once you get thru the sign in process (using your account credentials), it will give a 404 type page, but that's ok, the needed info is embedded in the url

Beyond that, I'm stuck... :-(

**Comment by areed1192** [comment]
I'm not sure if you've used this resource yet, but I have a guide in the following folder [Resources Folder](https://github.com/areed1192/td-ameritrade-python-api/tree/master/samples/resources/td-developer-account). In there you will see a PDF guide on how to create a Developer Account and the important information you'll need to keep for the client.

Please keep in mind that the **client_id** is this consumer ID, so you'll need that when you use the API library.

**Comment by reikred** [comment]
I have noted that areed1192 has updated README.md with some additional instructions on how an app has to be registered, which was helpful. But I still find the instructions confusing and the terminology inconsistent, both internally in this project docs+code, and relative to the Ameritrade developer docs, which also has some internal inconsistencies.

I'll try and fork a copy of README.md and annotate it with what I think it SHOULD say to make things easier to understand, I might get to that later today.

The good news: I have been able to login and get quotes. Thanks for creating this tool !!

**Comment by areed1192** [comment]
I also wanted to update you that there are now some videos on my YouTube Channel that go over using the library. I'll be adding that to the README as well. For the time being, I'm going to close the issue because it sounds like the original issue was solved.
