### ISSUE TITLE
Quick questions about authorization

### ISSUE THREAD

**Issue by wjaekim** [areed1192/td-ameritrade-python-api#140]
First, thank you so much for sharing your time and effort!

I cloned and installed from your repository, not from PYPI, and was able to create the credentials file.  I could read your code to resolve the following questions but you should be able to provide answers quickly:

1. How does the library handle expiration of a refresh token? I believe it cannot get a new one on its own. Will it give an alert to a console or a log file?
2. When an access token expires (after 30 mins) and an API request is made without the login method, I initially receive a "Not Authorized" error and on a 2nd request, it works. So, does this mean I should place login() before any request when there are time intervals between requests?

**Comment by shahbhaumik** [comment]
Hey @wjaekim  how did you get past to create the credential file?
i am getting stuck at point where it says unauthorized access 
this is actually text when i try to click on link link. At this point I don't have credential file and my call back url is http://localhost  
A third-party application may be attempting to make unauthorized access to your account. For help with your account, contact us. For information on securing your account, visit the TD Ameritrade Security page.

**Comment by wjaekim** [comment]
It seems that your callback URL in your TDA Developer App does not match what you enter in your authorization request.

**Comment by ehildebrandtrojo** [comment]
Something that worked for me is to always make sure to log off your Ameritrade developer account before pasting in the authentication URL generated by this API.
