### ISSUE TITLE
FYI See this repo with clean TD Ameritrade API schemas.

### ISSUE THREAD

**Issue by blais** [areed1192/td-ameritrade-python-api#146]
https://github.com/blais/ameritrade-api-schemas

**Comment by areed1192** [comment]
Out of curiosity, is it okay if I cover this at some point on my YouTube channel. I really like what you have here and I think a lot of people would find it useful.

**Comment by blais** [comment]
Absolutely.
Which part do you find interesting?
What's your channel?

**Comment by areed1192** [comment]
Well just the fact you managed to get all the endpoints in a JSON format where you can easily make any wrapper you want. Also, everything is just beautifully organized, I know people would find this useful. Here's my channel link: [Sigma Coding](https://www.youtube.com/channel/UCBsTB02yO0QGwtlfiv5m25Q)

**Comment by blais** [comment]
SGTM, go ahead.

I still need to put the polish on the repo - working on it this long
weekend - and convert to protocol buffer schemas.
I'm doing this for my Ameritrade bindings:
https://github.com/blais/ameritrade

This is adjacent to the Beancount universe of projects I'm building:
https://beancount.github.io/docs/
https://github.com/beancount/beancount

Happy to show up on your show as well if you think it's useful /
interesting,
In any case, send me a link if there's content on it.
Thank you,
