### ISSUE TITLE
please gut out this td_json thing and replace with a credentials object

### ISSUE THREAD

**Issue by cmpunches** [areed1192/td-ameritrade-python-api#149]
I would like to see this td_json concept removed, and replaced with a credentials object that the consuming implementer creates, or even just a constructor that takes credentials so that systems consuming the library can handle their own creds.

**Comment by areed1192** [comment]
Do you have an example of a library that implements this approach? I've been hearing mix reviews on this and I've been hesitant to implement something different because people prefer the current approach. However, if I can maintain the same experience I would be okay with a different approach.

**Comment by cmpunches** [comment]
To be honest, most libraries don't even do that. 

Calls take parameters for credentials, often in a credentials object that the consuming implementer constructs.  In OOP-driven models, you'll sometimes see a session driver object that will attach them as a child for them to reconstruct API calls and that's as many assumptions as you can really safely make.  Touching the filesystem to grab stored credentials for what could be a very large system consuming your library will not go well.

This is by design; the implementer consuming the library should worry about user credential i/o and just pass what is supplied to the calls.  This also allows consuming users to engage in safer password management practices like vault interaction to grab credentials to pass to your library.  It's important to remember that this is an interaction library for an existing service's API.  It could be consumed in a script, or a service in a larger system, maybe a desktop application that interacts with several services -- in such cases, one library that forces a credential scheme among potentially dozens that don't will make that library very awkward to work with.  When the app is interacting the with ameritrade API, suddenly they have to regress to a strange way of interacting with credentials to get their app to do things.

So if you're going to have anything, maybe just a credentials object with username/pass/apikey members that can be accessed by calling functions and removing any kind of credential caching on the filesystem altogether.

**Comment by cmpunches** [comment]
*I want to draw extra attention with a second post to the use case, which is highly likely for a library like this, where a user is building a system interacting with multiple authenticated services with different credentials -- forcing a credential storage or retrieval scheme on the user means that they now have to use their own configuration method on top of whatever the library is forcing them to do.

**Comment by areed1192** [comment]
@cmpunches I want to redirect you to the new repo for this project. I'm in the process of refactoring the code and want to get your opinion/input on the credentials/oAuth process. Here is the link to the new [td-repo](https://github.com/areed1192/td-ameritrade-api).

**Comment by cmpunches** [comment]
@areed1192 I appreciate that.  I'll check it out tonight.  Thanks in advance for the ear.

**Comment by cmpunches** [comment]
Thanks for the update.  This looks pretty good, and honestly, it's about as simple as it can get with their ridiculous oauth requirement.
