### ISSUE TITLE
I can't place order.

### ISSUE THREAD

**Issue by SunHxiao** [areed1192/td-ameritrade-python-api#15]
Hi, there.
I am very interested in your scripts.
I have run test scripts.
So all scripts works well
But the test_submit_order.py doesn't work right.
""""""""""""""""""
C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python.exe F:/td-ameritrade-python-api-master/tests/test_submit_order.py
{'session': 'NORMAL', 'duration': 'GOOD_TILL_CANCEL', 'orderType': 'LIMIT', 'orderStrategyType': 'SINGLE', 'price': 12.0, 'orderLegCollection': [{'instruction': 'BUY_TO_OPEN', 'quantity': 1, 'instrument': {'assetType': 'OPTION', 'symbol': 'MSFT_031320C155'}}]}
{"orderType": "MARKET", "session": "NORMAL", "duration": "DAY", "orderStrategyType": "SINGLE", "orderLegCollection": [{"instruction": "BUY", "instrument": {"assetType": "EQUITY", "symbol": "GIS"}, "quantityType": "SHARES", "quantity": 1}]}
**{'error': 'You do not have enough available cash/buying power for this order.'}**

I have get the error "'error': 'You do not have enough available cash/buying power for this order.'"
Would you please fix this error for me?
I will wait for your quick and favorable reply.
Thanks.

**Comment by MattsonThieme** [comment]
Not sure if this is the underlying issue, but have you checked that you indeed have the buying power for this order? With TD, if you aren't on a margin account, your buying power decreases each time you close a position, and will remain at that value until the order has settled (normally the next business day). Might be worth looking in My Account -> Balances -> Funds Available for Trading to make sure.

**Comment by SunHxiao** [comment]
Hi, MattsonThieme.
Thanks for your reply.
Sorry but would you please inform me in detail?
How to check the balance?
And I would like to know how to place future order(ex: /ES & /MES).
Can you help me?
I hope that I can get good advise from you, as an talented trading expert.
Best regards!

**Comment by MattsonThieme** [comment]
I meant to check in your actual TD Ameritrade account on the TD Ameritrade site. Once you've logged in to your TD account, under the "My Account" tab, select "Balances", then scroll down until you see "Funds Available for Trading". If that number is lower than the cost of one share of MSFT (what you've tried ordering above), then you'll probably have to wait until your last trades settle and the "Funds Available for Trading" comes back up.

**Comment by SunHxiao** [comment]
Oh,MattsonThieme.
Thanks for your nice help.
I would like to cancel the order.
By the way, I don't know how to get order_id.
Can you help me?

**Comment by areed1192** [comment]
You can get the order ID either by querying the `get_orders_query` method or the `get_orders_query` method from the TD Library. It sounds like the original issue you had with this post was solved so I'm going to close the issue.
