### ISSUE TITLE
CancelTime Format

### ISSUE THREAD

**Issue by greg12579** [areed1192/td-ameritrade-python-api#154]
I see that the code was updated to accept the cancelTime input. However I can't seem to figure out the format to make it work.
Any ideas?

**Comment by areed1192** [comment]
If you look [here](https://github.com/areed1192/td-ameritrade-python-api/blob/master/samples/orders/conditional%20order%20-%20trigger%20-%20OTA%20OCO.jsonc) you'll see an example of a cancel order.

**Comment by greg12579** [comment]
That may work but does not include the time. What if you wanted to cancel the order at 13:35PM?
It looks like issue #139 has a similar issue.  I see this as a potential fix. I can try it. 

`('cancelTime', {'date': '2020-12-14T14:30:00', 'shortFormat': False})`

**Comment by areed1192** [comment]
I would say try with that first and see what happens if it works, I'll add an example in the repo so other people can reference it. It's one of the issues where they never documented so it's just guessing and seeing what works.

**Comment by ckoehncke** [comment]
2023-12-01T23:00:00+0000
Got following { "error" : "Only dates without specific time are allowed for cancelTime." }

Tried using above cancel time, but got error, still searching

**Comment by ckoehncke** [comment]
Update, you can set a order to auto cancel on specific date (but not specific time), format is

[cancelTime] = "YYYY-MM-DD"
