### ISSUE TITLE
watchlist operations

### ISSUE THREAD

**Issue by freephys** [areed1192/td-ameritrade-python-api#157]
Try to create a new watchlist, I have tried below but no luck, Your help is greatly appreciated: 

w1 = watchlist_item.WatchlistItem(symbol='AAPL',assetType='EQUITY')
w1json = w1.create_watchlist_json()
w2 = watchlist_item.WatchlistItem(symbol='A',assetType='EQUITY')
w2json = w2.create_watchlist_json()

TDSession.create_watchlist(
                account = 'XXXXX', 
                name = 'check', 
                watchlistItems = w1json
            )

NotNulError: 
          {
        "error":"The Target endpoint cannot be reached or is not configured. Please check the request and try again"
      	   }

TDSession.update_watchlist(
                account = 'XXXXX', 
                watchlist_id = 'XXXXX', 
                name = 'check',
                watchlistItems = [w2json]
            )

GeneralError: {
  "error" : "Unsupported Media Type"
}

I tried to put w1 to replace w1json as well

**Comment by areed1192** [comment]
With watchlist management you need to have advanced features turned off on your account. Did you verify that?
