### ISSUE TITLE
Token Expired Error

### ISSUE THREAD

**Issue by Jmarks199** [areed1192/td-ameritrade-python-api#158]
I'm seeing an unexpected error and I was hoping there is some insight into the root cause. **The client seems to be unable to refresh the access token ONLY after the client has been running for 30 minutes.** Running `grab_access_token()` in the debugger prior to the token expiring does not throw any errors. But after the client has been connected for 30 minutes and then tries to request a new token, we get Unauthorized Error. Here is the code to reproduce.

        import time
        
        from td.client import TDClient
        
        TDSession = TDClient(
            client_id=CLIENT_ID,
            redirect_uri='http://localhost/authorizationcallback',
            credentials_path='C:/FULL/PATH/TO/JSON/FILE'
        )
        
        TDSession.login()
        
        while True:
            msft_quotes = TDSession.get_quotes(instruments=['MSFT'])
            print(msft_quotes)
        
            time.sleep(600)

Results in this stdout: 
>{'MSFT': {'assetType': 'EQUITY',}}
{'MSFT': {'assetType': 'EQUITY'}}
{'MSFT': {'assetType': 'EQUITY'}}
Grabbing new access token...
Traceback (most recent call last):
  File "scratch.py", line 15, in <module>
    msft_quotes = TDSession.get_quotes(instruments=['MSFT'])
  File "site-packages\td\client.py", line 747, in get_quotes
    return self._make_request(method='get', endpoint=endpoint, params=params)
  File "site-packages\td\client.py", line 619, in _make_request
    raise TknExpError(message=response.text)
td.exceptions.TknExpError: {"error":"Not Authorized."}

Reading through the code, i don't see any reason why the server would reject the request at this point. Any help is great, thanks. As an alternative is there any downside to calling `login()` periodically?

**Comment by SkyHyperV** [comment]
I'm getting the same error all of a sudden and my bot dies after an overnight "sleep". I have to re-start the script every morning.

**Comment by SkyHyperV** [comment]
Nevermind, tried and tested it.. still fails with that exception. I'm hoping dev or someone will respond with a solution.

**Comment by SkyHyperV** [comment]
Here's what I did and tested, in my try/except blocks where I am using "TDSession" to call get_quotes and other functions, I put except "td.exceptions.TknExpError" after I import the td library. It seems to have caught the exception and retried. Continuing to test.

**Comment by SkyHyperV** [comment]
My bot lived through the overnight with the caught exception... looking good so far.

**Comment by Jmarks199** [comment]
@SkyHyperV You are saying that in the event of TknExpError, you just retry the same function call but on the second try it succeeds?

**Comment by Jmarks199** [comment]
If you are running your program in an event loop, you can apparently keep it current by calling client.grab_access_token() periodically **before** it expires. Something like this:

`async def update_token(TDSession):

    refresh_time = datetime.datetime.now() + datetime.timedelta(minutes=25)
    while True:
        if datetime.datetime.now() > refresh_time:
            client.grab_access_token()
            refresh_time = datetime.datetime.now() + datetime.timedelta(minutes=25)
        else:
            await asyncio.sleep(60)

async def main(TDSession):
    asyncio.create_task(update_token(TDSession))
    await asyncio.sleep(.1)
   # rest of trading logic
`

If you aren't using coroutines, you may be able to run the update_token() in another thread, but I haven't tried it yet. Still not sure why the error occurs after the token is expired.

**Comment by SkyHyperV** [comment]
> @SkyHyperV You are saying that in the event of TknExpError, you just retry the same function call but on the second try it succeeds?

Yes, I do this throught my entire code. I have the first connection setup and get my TDSession object. Then I go into a while loop as my bot goes through various trades (open, monitor, close). In all of my try/excpt blocks, I added that exception from the 'td' library as part of my list of exceptions I catch and I just recall my last function that failed. Example bleow:

def cancel_order(logger, TDSession, order_id):

    logger.info(f"{BCOLORS.HEADER}[cancel_order]{BCOLORS.ENDC} entry")

    try:
        TDSession.cancel_order(account=ACCOUNT_NUMBER, order_id=str(order_id))
    except (TypeError, IndexError, TimeoutError, **td.exceptions.TknExpError**):
        logger.error(f"{BCOLORS.HEADER}[cancel_order]{BCOLORS.ENDC} cancel_order returned error. "
                     f"Retrying in {CONSTANTS.WAIT_SHORT} minute(s).")
        time.sleep(CONSTANTS.WAIT_SHORT * CONSTANTS.SECONDS_IN_MINUTE)
        cancel_order(logger, TDSession, order_id)

**Comment by areed1192** [comment]
I'm surprised that you're encountering this issue. The library is supposed to grab a new token 5 minutes before it's supposed expire and it checks the token each time a request is made. Which version of the library are you using?

**Comment by AdoNunes** [comment]
Same problem here. After I get the TknExpError with a not authorized error, if I just re-run the same code it goes through.

As a work around, in _make_request if that error is caught I re-run it once more

**Comment by areed1192** [comment]
I just wanted to update everyone that I added a minor fix to the `_make_request` method. Now if the status code is `401` it will first try to grab a new access token and if that fails it will then raise the token expire error as more than likely the user's Refresh token is expired and they need to go through the full authentication process again.

**Comment by SkyHyperV** [comment]
@areed1192  Can you push a new build so we can upgrade officially?

**Comment by areed1192** [comment]
> @areed1192 Can you push a new build so we can upgrade officially?

Pushed it:

```terminal
pip install td-ameritrade-python-api==0.3.5
```

**Comment by SkyHyperV** [comment]
Thanks @areed1192 awesome library!

**Comment by EklipZgit** [comment]
Fyi this library wasn't multiprocessing safe which might be related to this issue if you're still experiencing it. I'll have a pullrequest out shortly to make it MP safe.

**Comment by EklipZgit** [comment]
@areed1192 take a look at that PR, in the process of adding that multiprocessing-safety I'm pretty sure I found what causes this bug, an expired access token would still be sent if you waited long enough for the token to fully expire because the headers for the request were being set prior to actually checking if the token was expired. Should be fixed in my PR :)

**Comment by areed1192** [comment]
@EklipZgit your changes have been merged.

**Comment by areed1192** [comment]
Closing out since changes have been implemented.
