### ISSUE TITLE
Correct symbol names for $DJI, /CL and SPY.IV (indices, commodities and ETF intraday values)?

### ISSUE THREAD

**Issue by reikred** [areed1192/td-ameritrade-python-api#16]
In the standard Ameritrade thinkorswim software, one can get quotes for indices, for example $DJI, commodity prices, for example oil, symbol /CL, as well as intraday values of ETFs, for example SPY.IV is the name for the intraday value of the SPY ETF. But such symbols do not seem to work in the API. If I specify strings $DJI,  /CL or SPY.IV I get an error, whereas a simple stock symbol like MSFT works fine.

So: Does anyone know what is the correct symbol name, in the API, for fetching these types of quotes?

**Comment by areed1192** [comment]
Hi there,

I tried the symbols you listed up above and I didn't seem to have any issues when I made the request. Here is the request I made:

```python
# Test Futures, Indexes, and ETFs.
quotes_single = TDSession.get_quotes(instruments=['/CL', '$DJI', 'SPY'])
```

Let me know if that fixes the issue.
