### ISSUE TITLE
write_behavior not working

### ISSUE THREAD

**Issue by hrdymchl** [areed1192/td-ameritrade-python-api#17]
Hiya, thanks again for publishing this awesome library!

I have been using `test_streaming_client.py` as a template to stream options locally; however, I believe the csv writer doesn't execute. I have added extra logging to try to debug the situation but the logs do not mention any attempts to write to csv.

I'm not sure if this is an issue with the existing code or my edits.

Here's the code:

```
from td.client import TDClient
import logging

logging.basicConfig(level=logging.DEBUG)

# Create a new session
TDSession = TDClient(account_number=MY_USERNAME
                     account_password=MY_PASS
                     consumer_id=MY_ID,
                     redirect_uri='http://localhost,
                     json_path=None)

# Login to the session
TDSession.login()

# Create a streaming sesion
TDStreamingClient = TDSession.create_streaming_session()

# Set the data dump location
TDStreamingClient.write_behavior(file_path = "raw_data.csv", append_mode = True)

# Quality of Service
TDStreamingClient.quality_of_service(qos_level='express')

# Level One Option
TDStreamingClient.level_one_options(symbols=['SPY_051520P260'],fields=list(range(0, 42)))

# Stream it.
TDStreamingClient.stream()

```

**Comment by areed1192** [comment]
Thanks for bringing this issue up. The write behavior was failing because certain services were not approved to write yet. However, I'm in the process of adding those and validating each service. I'll update you once I release the update.

**Comment by areed1192** [comment]
Closing this out as it has been resolved. For more info on some of the changes being made refer to issue #29
