### ISSUE TITLE
the query param being passed is not in the correct format

### ISSUE THREAD

**Issue by BaconGabe** [areed1192/td-ameritrade-python-api#176]
**This works perfectly fine:**
`TDSession.get_accounts(account=account_id)`

**But adding a field like positions returns an error:**
`TDSession.get_accounts(account=account_id, fields=['positions'])`

**Error:** 
Traceback (most recent call last):
  File "C:\Users\Gabe\Desktop\Stock\test.py", line 47, in <module>
    print(TDSession.get_accounts(account=account_id, fields=['positions']))
  File "C:\Users\Gabe\AppData\Local\Programs\Python\Python39\lib\site-packages\td\client.py", line 1144, in get_accounts
    return self._make_request(method='get', endpoint=endpoint, params=params)
  File "C:\Users\Gabe\AppData\Local\Programs\Python\Python39\lib\site-packages\td\client.py", line 617, in _make_request
    raise NotNulError(message=response.text)
td.exceptions.NotNulError: 
          {
        "error":"the query param being passed is not in the correct format"
      		}
          

Process finished with exit code 1

**I've tried a lot and even different libraries but have no idea why this is happening. The same command works perfectly fine on the TD Ameritrade website, so why doesn't it work in the library?**

`print(TDSession.get_accounts(account=account_id, fields=['orders']))` also gives the same error

**Comment by BaconGabe** [comment]
`print(TDSession.get_accounts(account=account_id, fields=['orders']))` also gives the same error

**Comment by areed1192** [comment]
Interesting, what version of the library are you using? If you're not sure, just run the following code:

```python
import td

print(td.__version__)
```

**Comment by BaconGabe** [comment]
The version is 0.3.5, which is what installs when using pip
