### ISSUE TITLE
I would like to get open,high,low and close price in real-time.

### ISSUE THREAD

**Issue by SunHxiao** [areed1192/td-ameritrade-python-api#18]
I am very interested in this Github projects.
I am going to get AAPL open, high, low and close price in real-time.
So I am using level_one_quotes function for it.

TDStreamingClient.level_one_quotes(symbols=['AAPL'], fields=[0, 1, 2, 3, 4, 12, 13, 15, 28])
By the way, I can't get the prices now.
![image](https://user-images.githubusercontent.com/56060401/78708593-f6963e80-7944-11ea-868e-d86bd2a6f507.png)
I can get 1,2,3,4(ask,bid price) value correctly but I can't get 12,13,15,28(open,high,low and close price).
The prices doesn't come.
Can you help me?

**Comment by SunHxiao** [comment]
Hi Alex Reed.
Can you help me now?
I am waiting for your favorable reply now.
I am sure that you will help me.
Because you are a positive developer.
Best regards!

**Comment by SunHxiao** [comment]
Hi, MattsonThieme.
Your last help was very helpful to me.
I will never forget your polite and kind.
Can you help me?
I will look forward to your favorable reply.
Warm regards!

**Comment by areed1192** [comment]
Keep in mind that the TD API will only return data as it changes, so if there is no change in the underlying data then it won't return anything. Additionally, the streaming API seems to behave inconsistently if you don't pass through all the fields in sequential order.

I would recommend this, pass through all the fields and see what happens.

```python
# Level One Quote
TDStreamingClient.level_one_quotes(symbols=["SPY", "VOO"],  fields=list(range(0,29)))
```
