### ISSUE TITLE
Error retrieving options chain

### ISSUE THREAD

**Issue by lmsanch** [areed1192/td-ameritrade-python-api#2]
I am trying to retrieve option chain for an optionable sotck, for example, DD.
TDSessions has get_options_chains method, but I am probably no using it correctly. Could you please provide an example around retrieving option chains?

`TDSession.get_options_chain({'symbol': 'DD',
                             'strikeCount': 5,
                             'toDate': '2020-02-15'})`

Returns
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-d85b4ef1ae8a> in <module>
      1 TDSession.get_options_chain({'symbol': 'DD',
      2                              'strikeCount': 5,
----> 3                              'toDate': '2020-02-15'})

~/Documents/SGXCode/DWPA/td/client.py in get_options_chain(self, option_chain)
    930 
    931         # this request requires an API key, so let's add that.
--> 932         option_chain.add_chain_key(
    933             key_name="apikey", key_value=self.config["consumer_id"]
    934         )

AttributeError: 'dict' object has no attribute 'add_chain_key'

```
I can retrieve stock quotes w/o problems, so the authentications for my account is working fine.

**Comment by dvd9604** [comment]
Hey Imsanch,

`TDSession.get_option_chain` expects an instance of `OptionChain` as its argument, so you have to first create your option chain object then pass it to your request like below. 

```
# Import OptionChain class
from td.option_chain import OptionChain

# Create an instance of OC with your args
option_chain_1 = OptionChain(symbol='DD', strikeCount=5, toDate = '2020-02-15')

# Make API call for your chain by passing the option chain object
TDSession.get_options_chain(option_chain_1)
```
