### ISSUE TITLE
How to get real-time open prices?

### ISSUE THREAD

**Issue by jiany30** [areed1192/td-ameritrade-python-api#20]
![Screenshot_1](https://user-images.githubusercontent.com/62179052/78970051-05dedd00-7b3b-11ea-870e-3825f558923e.png)
I would like to get this plot in real-time.
Can you help me?
How to get this open prices via TD Ameritrade python API?
Best regards!

**Comment by areed1192** [comment]
You can use the `get_quotes` endpoint.

Here are some examples using the library:

```python
# `get_quotes` endpoint with single value. Should not return an error.
quotes_single = TDSession.get_quotes(instruments=['SQ'])

# `get_quotes` with a Options Contract
quotes_option_contract = TDSession.get_quotes(instruments=['MSFT_041720C75'])

# `get_quotes` with a Futures Contract
quotes_futures = TDSession.get_quotes(instruments=['/ES'])

# `get_quotes` with Forex
quotes_forex = TDSession.get_quotes(instruments=['AUD/USD'])
```
