### ISSUE TITLE
Account balances change after hours?

### ISSUE THREAD

**Issue by reikred** [areed1192/td-ameritrade-python-api#23]
I have observed that some of the account variables, for example "marginBalance" and "shortBalance" are not constant after market closing time, but rather are affected by after hours securities prices.
It also seems that Ameritrade does some final update of balances later in the evening, maybe around midnight EST, and I'm not even sure that these updates are consistent with the closing prices.

That seems a bit illogical to me. There should at least be an option that today's values reflect closing prices. One of the things I wanted to script was to check whether I need to sell something or transfer cash depending on margin balances (say 1 minute before closing), and it is aggravating that is hard to tell what the margin balance actually is (meaning: so I need to take action to avoid paying margin interest) because the numbers do not reflect closing prices and keep changing, AFAICT.

I realize that balances not reflecting closing is not the fault of this library, but rather a "feature" of the Ameritrade API. But does anyone else have any thoughts about how to fix this problem?

**Comment by areed1192** [comment]
When you ran into this problem did you check the other balances to see if they contain the correct information?

When you make a request to the `accounts` endpoint you should see a `currentBalance`, `initalBalance`, and `projectedBalance`. Were all three of those incorrect?
