### ISSUE TITLE
Gethistory Problem

### ISSUE THREAD

**Issue by baomx888** [areed1192/td-ameritrade-python-api#24]
I ran the get_price_history yesterday using 10 days parameters and downloaded 10 days ending 4/13/2020.  Today I rerun the same code.  I assume that I could get 10 days ending 4/14/2020.  
But I still get the same data as yesterday.   I restarted Pycharm and still the same.  I have to specify startdate and enddate as shown in the second part of the code. 

`TDSession.login()
histdata=TDSession.get_price_history(symbol='C',periodType='day',period=10,frequencyType='minute',frequency=1,needExtendedHoursData='false')

endtimestamp = int (datetime.datetime(2020, 4, 14, 23, 59).timestamp())*1000
starttimestamp = int (datetime.datetime(2020, 4, 4, 23, 59).timestamp())*1000
histdata=TDSession.get_price_history(symbol='C', periodType='day', startDate=starttimestamp, endDate=endtimestamp,frequencyType='minute',frequency=1,needExtendedHoursData='false')
`

**Comment by areed1192** [comment]
When I use the datetimes, I prefer to use the `timedelta` object to build the other date. For example, here is a custom 31-day range.

```python
# The max look back period for minute data is 31 Days.
lookback_period = 31

# Define today.
today_00 = datetime.now()

# Define 300 days ago.
today_ago = datetime.now() - timedelta(days=lookback_period)

# The TD API expects a timestamp in milliseconds. However, the timestamp() method only returns to seconds so multiply it by 1000.
today_00 = str(int(round(today_00.timestamp() * 1000)))
today_ago = str(int(round(today_ago.timestamp() * 1000)))

# These values will now be our startDate and endDate parameters.
hist_startDate = today_ago
hist_endDate = today_00

# Define the dynamic arguments, PERIOD IS NOT NEEDED!!!!
hist_periodType = 'day'
hist_frequencyType = 'minute'
hist_frequency = 1

hist_needExtendedHoursData = False

# Make the request
historical_custom = TDSession.get_price_history(
    symbol=hist_symbol, 
    periodType=hist_periodType,
    frequencyType=hist_frequencyType,
    startDate=hist_startDate,
    endDate=hist_endDate,
    frequency=hist_frequency,
    needExtendedHoursData=hist_needExtendedHoursData
) 
```

Let me know if that fixes the issue.

**Comment by baomx888** [comment]
Thanks... This is faster than mine!

**Comment by areed1192** [comment]
Since the issue has been resolved, I'll be closing the issue.
