### ISSUE TITLE
Streaming Example

### ISSUE THREAD

**Issue by SkyHyperV** [areed1192/td-ameritrade-python-api#242]
Anyone have an example of how to stream symbols with this library? I have a basic function setup that prints to console but I want to handle it in a thread. Here's what I have...

def stream_option_symbols(logger, TDSession, symbols)

    TDStreamingClient = TDSession.create_streaming_session()
    TDStreamingClient.quality_of_service(qos_level='delayed')

    def handle_message(message):
        print(message)

    # testing various ones
    TDStreamingClient.account_activity()
    TDStreamingClient.level_one_options(symbols=symbols, fields=list(range(0, 4)))

    TDStreamingClient.build_pipeline()
    TDStreamingClient.start_pipeline()
    TDStreamingClient.stream(print_to_console=False)

    while True:
        await TDStreamingClient.handle_message()

**Comment by mpermana** [comment]
```
async def run(symbols):
    td_stream_session = TDSession.create_streaming_session()
    td_stream_session.level_one_quotes(symbols, fields=list(range(53)))
    connection = await td_stream_session._connect()
    data_request = td_stream_session._build_data_request()
    await td_stream_session._send_message(data_request)
    while True:
        message = await connection.recv()
        data = loads(message).get('data', [])
        if data:
            print(data)

if __name__ == '__main__':
    symbols = argv[1:] or ['QQQ']
    loop = new_event_loop()
    loop.run_until_complete(run(symbols))

```

**Comment by regholl** [comment]
thank you,i'm going to assume that i need to make a whole new file with
just this script in it?
