### ISSUE TITLE
Streaming Data saving and reading issue

### ISSUE THREAD

**Issue by baomx888** [areed1192/td-ameritrade-python-api#25]
I am trying to create a streaming session with three tickers. I do see the message in terminal.  But nothing saved in the csv file.  Also How could I read the streaming message and process the data? Thanks!

`# Login to the session
TDSession.login()
# Create a streaming sesion
TDStreamingClient = TDSession.create_streaming_session()
print(TDStreamingClient.websocket_url)

TDStreamingClient.write_behavior(write='csv',file_path = 'E:\\TD\\samples\\raw.csv', append_mode = True)

TDStreamingClient.level_one_quotes(symbols=['APA','BKR','COG','COP'],  fields=list(range(0,8)))

# Stream it.
TDStreamingClient.stream()
TDStreamingClient.approved_writes()
`

**Comment by areed1192** [comment]
Here is an example of writing level one quotes to a CSV file:

```python
# Login to the session
TDSession.login()

# Create a streaming session
TDStreamingClient = TDSession.create_streaming_session()

# Set the data dump location
TDStreamingClient.write_behavior(file_path "PATH_TO_FILE", append_mode=True)

# Level One Quote
TDStreamingClient.level_one_quotes(symbols=["SPY", "VOO"],  fields=list(range(0,8))

# Stream it.
TDStreamingClient.stream()
```

Let me know how that works for you.

**Comment by baomx888** [comment]
I just updated the code with new path.  
I can see the streaming message in message box and none is saved in the csv I designated. 

`# Login to the session
TDSession.login()

# Create a streaming session
TDStreamingClient = TDSession.create_streaming_session()

# Set the data dump location
TDStreamingClient.write_behavior(file_path="E:\\TD\\samples\\raw.csv", append_mode=True)

# Level One Quote
TDStreamingClient.level_one_quotes(symbols=["SPY", "VOO"],  fields=list(range(0,8)))

# Stream it.
TDStreamingClient.stream()`

**Comment by baomx888** [comment]
Alex, besides the csv files saving option, how can I access the streaming quote? I can see the streaming data come in but have no idea how to access those.  Thanks!

**Comment by areed1192** [comment]
I'm going to refer you to the enhancement, we opened for adding a data pipeline. Here is the link: #29
