### ISSUE TITLE
Some suggestions for restructuring

### ISSUE THREAD

**Issue by themantalope** [areed1192/td-ameritrade-python-api#27]
Hi @areed1192 this is a really nice repo! Have a couple suggestions for you

1) I would recommend keeping all user-specific data (so any config information and the State.json file) in a directory for the user. Pretty simple way to set that up in the `setup.py` file would be to do something like:

```python
import os
home_dir = os.path.expanduser('~')
td_dir = os.path.join(home_dir, '.tdunofficial')
if not os.path.isdir(td_dir): os.makedirs(td_dir)
```

Then you should save anything the user needs or wants to use in here. Removes the problem of saving user-specific information in the repo.

2) Use a config file. I would set up a config file (the `.ini` file with the python [configparser](https://docs.python.org/3.7/library/configparser.html_) tends to be used for many python projects, and is shipped with python). You can set up a default config file, which the `TDClient` object loads during `__init__`, ships with the package and gets installed to the `td_dir` as discussed above. The user can then edit the config file as they please. Would also recommend that a path to a config file get supplied to the `__init__` method, with the default one as discussed above.

Anyways, take them or leave them. I submitted a PR for another thing I wanted to add to. Let me know if you need a hand implementing these.

-themantalope

**Comment by mLewisLogic** [comment]
For #1, I'd ask that a different approach is taker. Or at least continue to allow user-specified userdirs.
I don't want to clutter or leak my creds into my dotfiles. It is also not a flexible solution for managing multiple sets of creds.

For #2, just curious, what's the use case not covered by the json file? I'm assuming that the contents of the ini are basically just `**kwargs` into `TDClient`?

**Comment by areed1192** [comment]
So I started looking more into the whole process of writing to the JSON file and what I decided to do was create a separate class object called `StatePath` that would handle all the write and read operations to the JSON file. Additionally, I added checks to make sure that the directory exist, the file exists, and so on.

I'm also working on enhancing the custom path, so it can do the same checks.

**Comment by Kreationz79** [comment]
This is what I currently use to load my credentials:

```python
import configparser

config = configparser.ConfigParser()
config.read('config.ini')

CONSUMER_KEY = config.get('Default', 'CONSUMER_KEY')
REDIRECT_URI = config.get('Default', 'REDIRECT_URI')
TD_ACCOUNT = config.get('Default', 'TD_ACCOUNT')
JSON_PATH = config.get('Default', 'JSON_PATH')

#This is how it looks in config.ini
"""
[Default]
CONSUMER_KEY = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
REDIRECT_URI = https://localhost/
JSON_PATH = C:/MyPath/td_state.json
TD_ACCOUNT = ##########
"""
```
I do that to allow me to distribute my code to others without needing to remove personal data.

**Comment by Kreationz79** [comment]
As a side note for those with multiple accounts the config.ini can be set up to handle multiple accounts:

>[Global]
CONSUMER_KEY = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
REDIRECT_URI = https://localhost/
>
> [Account1]
JSON_PATH = C:/MyPath/td_state1.json
TD_ACCOUNT = ##########
>
>[Account2]
JSON_PATH = C:/MyPath/td_state2.json
TD_ACCOUNT = ##########

You will need multiple JSON's to store the credentials for each account, but the values under global are for the developer account.
