### ISSUE TITLE
How to dynamically add streams?

### ISSUE THREAD

**Issue by lacabra** [areed1192/td-ameritrade-python-api#29]
Hi @areed1192, first and foremost, thank you very much for writing this code, and making it available. I started it using a couple days ago, and it works very well for me.

I have a question for you: how would you go about dynamically changing the streams that we are subscribed to? I am looking at subscribing to ATM calls for a given stock, so as the stock price changes, I want to unsubscribe from the no-longer-ATM call, and subscribe to the new ATM call. 

I presume I would need to close the stream, and open it again with the new stream; but because the stream call is blocking, then my program logic halts. I would need to be able to "fork" the streaming start so that is not blocking. 

Curious to hear your thoughts... :)

**Comment by baomx888** [comment]
Would you mind sharing how you read the streaming data?  It seems the csv write function is not working properly.   I can see streaming data in the terminal but has no idea on how to fetch the data for calculation.

**Comment by lacabra** [comment]
Sure, @baomx888.

I am not using the provided csv write function because I want to process the data realtime as it comes, so I am not interested in writing it to a file. I keep everything in memory for now... To that end, I'm extending the default class provided and my own function so that every time some data comes in, gets processed there. Relevant snipped code included below:

```python
from td.client import TDClient
from td.stream import TDStreamerClient

def processData(data):
    if 'data' in data.keys():
         # Do real time data processing here...
         pass

class MyStreamer(TDStreamerClient):
    async def _receive_message(self, connection):
        '''
            Receiving all server messages and handle them.
            NAME: connection
            DESC: The WebSocket Connection Client.
            TYPE: Object
        '''

        # Keep going until cancelled.
        while True:

            try:

                # recieve and decode the message.
                message = await connection.recv()
            
                try:
                    message_decoded = json.loads(message)
                except:
                    message = message.encode('utf-8').replace(b'\xef\xbf\xbd', bytes('"None"','utf-8')).decode('utf-8')
                    message_decoded = json.loads(message)

                # if 'data' in message_decoded.keys():                     
                #     await self._write_to_csv(data = message_decoded['data'])

                # print('-'*20)
                # print('Received message from server: {}'.format(str(message_decoded)))
                processData(message_decoded)

            except websockets.exceptions.ConnectionClosed:

                # stop the connection if there is an error.
                print('Connection with server closed')
                break

class MyClient(TDClient):

    def create_streaming_session(self):
        '''
            Creates a new streaming session that can be used to stream different data sources.
            RTYPE: TDStream Object
        '''
        
        # Grab the Streamer Info.
        userPrincipalsResponse = self.get_user_principals(
            fields=['streamerConnectionInfo','streamerSubscriptionKeys','preferences','surrogateIds'])

        # Grab the timestampe.
        tokenTimeStamp = userPrincipalsResponse['streamerInfo']['tokenTimestamp']

        # Grab socket
        socket_url = userPrincipalsResponse['streamerInfo']['streamerSocketUrl']

        # Parse the token timestamp.
        tokenTimeStampAsMs = self._create_token_timestamp(
            token_timestamp=tokenTimeStamp)

        # Define our Credentials Dictionary used for authentication.
        credentials = {"userid": userPrincipalsResponse['accounts'][0]['accountId'],
                       "token": userPrincipalsResponse['streamerInfo']['token'],
                       "company": userPrincipalsResponse['accounts'][0]['company'],
                       "segment": userPrincipalsResponse['accounts'][0]['segment'],
                       "cddomain": userPrincipalsResponse['accounts'][0]['accountCdDomainId'],
                       "usergroup": userPrincipalsResponse['streamerInfo']['userGroup'],
                       "accesslevel": userPrincipalsResponse['streamerInfo']['accessLevel'],
                       "authorized": "Y",
                       "timestamp": tokenTimeStampAsMs,
                       "appid": userPrincipalsResponse['streamerInfo']['appId'],
                       "acl": userPrincipalsResponse['streamerInfo']['acl']}

        # Create the session
        streaming_session = MyStreamer(websocket_url=socket_url, user_principal_data=userPrincipalsResponse, credentials=credentials)

        return streaming_session

# Create a new session
TDSession = MyClient(
    consumer_id='...',
    redirect_uri='...',
    json_path='...'
)

TDStreamingClient = TDSession.create_streaming_session()

# Select whatever stream you want here

TDStreamingClient.stream()
```

**Comment by baomx888** [comment]
Many Thanks!!!  That is what I intend to do the calculation as well.  I want to skip csv writing and reading to accelerate as well.

**Comment by areed1192** [comment]
Howdy, so this has been a highly requested feature and I've been working on it. Right now, I've been modifying the Streaming Client so that it includes some new methods and simplifying some existing ones.

In your situation, I would call it a data pipeline. Where the data comes in, you take it and process it. Here is how the new pipeline functionality would look:

```python

import asyncio
from td.client import TDClient

# Create a new session
td_session = MyClient(
    client_id='...',
    redirect_uri='...',
    credentials_path='...'
)

# Create a new instance of the streaming client.
td_stream_client = td_session.create_streaming_session()

# This would be a separate function that does all the data processing. 
async def data_pipeline():

   # subscribe to services just like you did before.
    td_robot.td_stream_client.level_one_futures(
        symbols=['/CL'],
        fields=list(range(0,38))
    )
    
   # Build the pipeline.
    await td_robot.td_stream_client.build_pipeline()
  
   # Keep going, as long as we have data.
    while True:
         
         # Grab the data.
         data = await td_robot.td_stream_client.start_pipeline()
        
        # Do something with it.
         if 'data' in data:
            pprint.pprint(data['data'][0]['content'])

# Use Asyncio to run the pipeline.
asyncio.run(data_pipeline())
```

**Comment by baomx888** [comment]
Thanks for the quick reply!  What is the credentials_path?  I assume client_id is the application ID not the TD login.   The redirect_url is http://localhost as of now.

**Comment by lacabra** [comment]
@baomx888 that's the path to your `TDAmeritradeState.json` file where your credentials are stored. This file is likely to be in the same folder where you have your python script, in that case that line would read:
```python
   credentials_path='TDAmeritradeState.json'
```

**Comment by lacabra** [comment]
Thanks @areed1192 for your reply, but I do not think that what you are proposing addresses my request. What I am hearing is that I can schedule data pipelines at predefined intervals, which is good, but that's not what I'm asking. I want to change subscriptions on-the-fly: say I'm subscribed to one stream, and depending on what I get on that stream, I then want to add another stream.

**Comment by areed1192** [comment]
Hey, @lacabra, so more than likely, I will have to integrate that the functionality so that when you call a service, you could specify whether to unsubscribe or not. To do that real-time, as data streams in, you will still need to follow a framework that I presented above.

The reason being is because some of the functions will be synchronous while others won't, so you would have to explicitly call `await` to make sure that the service is unsubscribed from. I'll work on it this weekend and try to get an example up so you can see it.

Thanks for the suggestion.

**Comment by RossGlengarry** [comment]
Thanks Alex, I'm interested in this as well -- your efforts are much
appreciated.

Cheers

**Comment by baomx888** [comment]
Alex, Where can I get the field description for the streaming data.  I found one in your code but your level1 stock data is returning 42 fields while your header is showing 43 fields.  Can u point me to the right document for the reference?
Thanks!



account_activity_fields = ['subscription-key',
                           'account-id', 'message-type', 'message-data']
level_one_forex_fields = ['symbol', 'bid-price', 'ask-price', 'last-price', 'bid-size', 'ask-size', 'total-volume',
                          'last-size', 'trade-time', 'quote-time', 'high-price', 'low-price', 'close-price',
                          'exchange-id', 'description',
                          'digits', 'open-price', 'net-change', '52-week-low', 'exchange-name', 'security-status',
                          'mark', 'tick', 'tick-amount', 'product', 'percent-change', 'trading-hours', 'is-tradable',
                          'market-maker', '52-week-high']
level_one_futures_fields = ['symbol', 'bid-price', 'ask-price', 'last-price', 'bid-size', 'ask-size', 'ask-id',
                            'bid-id', 'total-volume', 'last-size', 'trade-time', 'quote-time', 'high-price',
                            'low-price', 'close-price', 'exchange-id', 'description', 'last-id', 'open-price',
                            'net-change',
                            'security-status', 'mark', 'open-interest', 'future-percent-change', 'exhange-name', 'tick',
                            'tick-amount', 'product', 'future-price-format', 'future-trading-hours',
                            'future-is-tradable', 'future-multiplier', 'future-is-active', 'future-settlement-price',
                            'future-active-symbol', 'future-expiration-date']
level_one_futures_options_fields = ['symbol', 'bid-price', 'ask-price', 'last-price', 'bid-size', 'ask-size', 'ask-id',
                                    'bid-id', 'total-volume', 'last-size', 'trade-time', 'quote-time', 'high-price',
                                    'low-price', 'close-price', 'exchange-id', 'description', 'last-id', 'open-price',
                                    'net-change',
                                    'security-status', 'mark', 'open-interest', 'future-percent-change', 'exhange-name',
                                    'tick', 'tick-amount', 'product', 'future-price-format', 'future-trading-hours',
                                    'future-is-tradable', 'future-multiplier', 'future-is-active',
                                    'future-settlement-price', 'future-active-symbol', 'future-expiration-date']
level_one_option_fields = ['symbol', 'bid-price', 'ask-price', 'last-price', 'bid-size', 'ask-size', 'total-volume',
                           'last-size', 'trade-time', 'quote-time', 'high-price', 'low-price', 'close-price',
                           'quote-day', 'trade-day', 'volatility', 'description', 'digits', 'open-price', 'net-change',
                           'security-status', 'mark',
                           'open-interest', 'money-intrinsic-value', 'expiration-year', 'multiplier', 'strike-price',
                           'contract-type', 'underlying', 'expiration-month', 'deliverables', 'time-value',
                           'expiration-day', 'days-to-expiration', 'delta', 'gamma', 'theta', 'vega', 'rho',
                           'theoretical-option-value', 'underlying-price', 'uv-expiration-type']
level_one_quote_fields = ['symbol', 'bid-price', 'ask-price', 'last-price', 'bid-size', 'ask-size', 'ask-id', 'bid-id',
                          'total-volume', 'last-size', 'trade-time', 'quote-time', 'high-price', 'low-price',
                          'bid-tick', 'close-price', 'exchange-id', 'marginable', 'shortable', 'island-bid',
                          'island-ask', 'island-volume', 'quote-day', 'trade-day', 'volatility', 'description',
                          'last-id', 'digits', 'open-price', 'net-change', '52 -week-high', '52-week-low',
                          'pe-ratio', 'dividend-amount', 'dividend-yield', 'island-bid-size', 'island-ask-size', 'nav',
                          'fund-price', 'exchange-name', 'dividend-date', 'regular-market-quote',
                          'regular-market-trade', 'regular-market-last-price', 'regular-market-last-size',
                          'regular-market-trade-time', 'regular-market-trade-day', 'regular-market-net-change',
                          'security-status', 'mark', 'quote-time-in-long', 'trade-time-in-long',
                          'regular-market-trade-time-in-long']
news_headline_fields = ['symbol', 'error-code', 'story-datetime', 'headline-id', 'status',
                        'headline', 'story-id', 'count-for-keyword', 'keyword-array', 'is-hot', 'story-source']
qos_request_fields = ['express', 'real-time',
                      'fast', 'moderate', 'slow', 'delayed']
timesale_fields = ['symbol', 'last-price',
                   'last-size', 'trade-time', 'last-sequence']
chart_fields = ['key', 'open-price', 'high-price', 'low-price',
                'close-price', 'volume', 'sequence', 'chart-time', 'chart-day']

**Comment by lacabra** [comment]
@baomx888, refer to TD Ameritrade Developer documentation, specifically the Streaming section, all the information that you need is here:

https://developer.tdameritrade.com/content/streaming-data

**Comment by baomx888** [comment]
@lacabra  Thanks a Million!!!!!

**Comment by lacabra** [comment]
@areed1192, I believe there are different ways to accomplish the same functionality. After some trial and error I have a slightly different implementation that works very well for me, which can be described in broad strokes as:

1. Make `TDStreamerClient` a subclass of `threading.Thread`:

```python
class TDStreamerClient(threading.Thread):
```

which allows to start an instance of the client in a different thread, making it non-blocking and allowing to do other things on the main thread.

2. As a result of item 1 above, rename `stream()` class function to `run()`, which gets called by the underlying thread class upon calling `client.start()`. As the [documentation says](https://docs.python.org/2/library/threading.html#thread-objects) only `__init__()` and `run()` should be overriden in the Thread class, so we are good.

3. This item is not directly related, but I believe is an improvement, and allows the thread to be terminated gracefully. Replace `self.loop.run_forever()` by:

```python
        try:
            self._loop.run_until_complete(self._stop_event.wait())
            self._loop.run_until_complete(self._clean())
        finally:
            self._loop.close()
```

4. One can then run `start()` in a non-blocking way, and at any point create a task to add a stream at any time along the lines of:

```python
    task = self._loop.create_task(self._add_stream(topic, sub_msg, self.callback))
    self._tasks[topic] = task
```

where `._add_stream` is:

```python
    async def _add_stream(self, topic, sub_msg, callback):
        await self.connection.send(json.dumps(sub_msg))
```

but it does not get awaited, as it is launched as a parallel task. One needs to keep track of the tasks that have been launched and clean them properly at the end, but in this case, these simply end when the request is made.

Anyway, I am just highlighing some of the functionality, there are some small changes here and there to glue all this together, but it works really well for me. I can submit a PR for your review if you are interested... just let me know.

**Comment by areed1192** [comment]
Alright, so I made some of the changes today. The big one was adding an `unsubscribe` method to the streaming client so that we can now unsubscribe from services midstream. Additionally, I made some modifications to the `close_stream` method to help simplify it and at the same time help it close the event loop more gracefully.

You can now see an example of doing all of this in the `api_pipeline.py` file. Keep in mind, that when you run this during the weekend you'll get different results because most of the services aren't running. Here is the main function inside of it:

```python
# Create a new session
TDSession = TDClient(
    client_id=config.CLIENT_ID,
    redirect_uri=config.REDIRECT_URI,
    credentials_path=config.JSON_PATH
)

# Login to the session
TDSession.login()

# Create a streaming session
TDStreamingClient = TDSession.create_streaming_session()

# Level One Quote
TDStreamingClient.level_one_quotes(symbols=["SPY", "IVV", "SDS", "SH"], fields=list(range(0,50)))

# Level One Option
TDStreamingClient.level_one_futures(symbols=['/ES'], fields=list(range(0,42)))

# Data Pipeline function
async def data_pipeline():
    """
    This is an example of how to build a data pipeline,
    using the library. A common scenario that would warrant
    using a pipeline is taking data that is sent back to the stream
    and processing it so it can be used in other programs or functions.

    Generally speaking, you will need to wrap the operations that process
    and handle the data inside an async function. The reason being is so
    that you can await the return of data.

    However, operations, like creating the client, and subscribing to services,
    can be performed outside the async function. In the example below, we demonstrate 
    building the pipeline, which is connecting to the WebSocket and logging in.

    We then start the pipeline, which is where the services are subscribed to and data
    begins streaming. The `start_pipeline()` will return the data as it comes in. From
    there, we process the data however we choose.

    Additionally, we can also see how to unsubscribe from a stream using logic and how
    to close the socket mid-stream.
    """

    data_response_count = 0
    heartbeat_response_count = 0

    # Build the Pipeline.
    await TDStreamingClient.build_pipeline()

    # Keep going as long as we can recieve data.
    while True:
        
        # Start the Pipeline.
        data = await TDStreamingClient.start_pipeline()
       
        # Grab the data if there was any. Remember not every message will have `data.`
        if 'data' in data:

            print('='*80)

            data_content = data['data'][0]['content']
            pprint.pprint(data_content, indent=4)

            # Here I can grab data as it comes in and do something with it.
            if 'key' in data_content[0]:
                print('Here is my key: {}'.format(data_content[0]['key']))

            print('-'*80)
            data_response_count += 1
        
        # If we get a heartbeat notice, let's increment our counter.
        elif 'notify' in data:
            print(data['notify'][0])
            heartbeat_response_count += 1

        # Once we have 1 data responses, we can unsubscribe from a service.
        if data_response_count == 1:
            unsub = await TDStreamingClient.unsubscribe(service='LEVELONE_FUTURES')
            data_response_count += 1
            print('='*80)
            print(unsub)
            print('-'*80)

        # Once we have 5 heartbeats, let's close the stream. Make sure to break the while loop.
        # or else you will encounter an exception.
        if heartbeat_response_count == 3:
           await TDStreamingClient.close_stream()
           break

# Run the pipeline.
asyncio.run(data_pipeline())
```

**Comment by gamesover** [comment]
Can we keep stream/websocket forever running?
```python
TDStreamingClient = TDSession.create_streaming_session()
TDStreamingClient.account_activity()

async def data_pipeline():
    await TDStreamingClient.build_pipeline()
    while True:
      # Start the Pipeline.
      data = await TDStreamingClient.start_pipeline()
      if data and not data.get('notify'):
        print(data)

asyncio.run(data_pipeline())
```
I keep running the above program for a period of time. It will report the below error
```
Connection with server closed, beginning close process...
Event loop was not closed.
```
It seems we cannot forever keep websocket stream from client connected to server?

**Comment by areed1192** [comment]
@gamesover The stream won't stay open if you have an empty subscription because eventually, TD will disconnect.

**Comment by gamesover** [comment]
Thanks for the answer @areed1192 . It explains why :+1: 

Originally, I want to use stream to subscribe the order status. E.G., when the order status becomes filled, I can take some actions from my side. It seems I need to choose alternative solutions.

Is there a way to keep websocket forever connected?

**Comment by Kreationz79** [comment]
@gamesover You should be able to add a subscription so that you can keep streaming the non-subscription data or add an error handling routine to restart the subscription if the connection is lost.

**Comment by trades4x** [comment]
> Hi @areed1192, first and foremost, thank you very much for writing this code, and making it available. I started it using a couple days ago, and it works very well for me.
> 
> I have a question for you: how would you go about dynamically changing the streams that we are subscribed to? I am looking at subscribing to ATM calls for a given stock, so as the stock price changes, I want to unsubscribe from the no-longer-ATM call, and subscribe to the new ATM call.
> 
> I presume I would need to close the stream, and open it again with the new stream; but because the stream call is blocking, then my program logic halts. I would need to be able to "fork" the streaming start so that is not blocking.
> 
> Curious to hear your thoughts... :)

my scenario is slightly different that my watchlist will change many times during the day, **so will I also need to subscribe and unsubscribe to see streaming stock and option prices for new stocks added the watchlist**

my options that I was watching are not changing, only new stock and/or options get added to the watchlist

**Comment by weiguang-zz** [comment]
What the build_pipeline method returns is data, not a pipeline, which is not easy to understand. Why not implement it through callbacks, that is, users can process data by registering callback methods with TDClientStreamer.
 ```

# Create a new session
TDSession = TDClient(
    client_id=config.CLIENT_ID,
    redirect_uri=config.REDIRECT_URI,
    credentials_path=config.JSON_PATH
)

# Login to the session
TDSession.login()

# Create a streaming session
TDStreamingClient = TDSession.create_streaming_session()

# Level One Quote
TDStreamingClient.level_one_quotes(symbols=["SPY", "IVV", "SDS", "SH"], fields=list(range(0,50)))

# Level One Option
TDStreamingClient.level_one_futures(symbols=['/ES'], fields=list(range(0,42)))

def process_data(data):
     # you logic to process the data
     pass


TDStreamingClient.register_callback(process_data)
TDStreamingClient.stream(print_to_console=False)

```
