### ISSUE TITLE
Break out message parsing request

### ISSUE THREAD

**Issue by inventor2525** [areed1192/td-ameritrade-python-api#30]
Hey @areed1192 ,

First, thanks for all the hard work figuring out all these undocumented endpoints and the whole api!!

I'm wondering though if we could break the csv saving, message parsing & building, and message flattening out of the stream and client classes?

Reasons for this would include:
1. Easier for others to contribute to smaller pieces, with less merge conflicts
2. Adds the possibility to create a moc stream and client to facilitate message parsing unit tests and to aid in their development, utilizing saved message streams to test with
3. Easier for users to learn and look over the client and stream code if they want to sub class them, learn their use, or even just for their own peace of mind (especially as this grows, I imagine more people will want to do that with a financial api wrapper)

Take or leave it, but curious to hear any thoughts!

If it's needed, I've included some sudo py to hopefully add some clarity: [Example_BreakOut.txt](https://github.com/areed1192/td-ameritrade-python-api/files/4533522/Example_BreakOut.txt)

**Comment by areed1192** [comment]
You read my mind! :)

I added some of what you're asking for today with regards to the CSV file, but I think there is still some more work to do. 

Regarding the messages, I really like how you're looking at the message as a class object; I think that makes a lot of sense. Additionally, I think that's going to make it more comfortable to work with and promote clarity like you're saying.

I'll try to add that change later this weekend. When I add it, I'll let you know, and I'd like to get your input on it.

**Comment by inventor2525** [comment]
Awesome! -- I'd be happy to give er a look!

Might want to tag or branch before though, un-fortunately this will be a pretty breaking change.

**Comment by areed1192** [comment]
Alright, I added the initial framework to the library, as a separate file called `message.py`. I also created a new branch that you should be able to access to see the initial work on it.

The branch is called [add-message-class](https://github.com/areed1192/td-ameritrade-python-api/tree/add-message-class).

Take a look and let me know what you think at the initial approach.

**Comment by inventor2525** [comment]
Cool! -- I went ahead and attached my comments.
[td api mod thoughts.pdf](https://github.com/areed1192/td-ameritrade-python-api/files/4584553/td.api.mod.thoughts.pdf)

There was some other stuff but message, so apologies if I covered random in-dev stuff, I just covered the whole branch's changes.

**Comment by areed1192** [comment]
@inventor2525 I took a look at what you sent and I agree with most of it. I'm going to start making some additional changes and then send you an update.

### Streaming Message Components:
It sounds like you are thinking of the components as completely separate entities, correct? Initially, the reason I started with a "collection" of components, is that a message can receive multiple responses at once. The responses each represent a different service you subscribed to. 

From there, I would take each of the services and break them into a `component` that represents a single service from a message. That was my thought on it. However, you're thinking it would be best to just convert the message into the different `components` and return those back as a list, for example. Correct?

### StatePath
Also, yes, the `defaults.py` is probably going to be the new path forward for saving and loading states.

**Comment by inventor2525** [comment]
@areed1192  Yeah, Thats exactly what I was thinking with the streaming message components

Like I said, I'm not sure of any services that need to be specifically bundled together, like that. Maybe you are thinking of some messages that would? I mean, either would work, but from what I can tell the only reason they bundle them is to save on total messages going over the underlying network protocols which them selves have their own overhead. -- I don't think that should be reason to structure the user facing api in that manner though, if indeed it is the only reason.

I could probably fork and wip up a version as an example of what I'm thinking if it would help?
