### ISSUE TITLE
ModuleNotFoundError: No module named 'config.credentials'

### ISSUE THREAD

**Issue by kiwi18** [areed1192/td-ameritrade-python-api#32]
Hi, i'm upgrading from 0.2.3 to 0.2.6 and ran into the following error when running test_regular_client.py

ModuleNotFoundError: No module named 'config.credentials'

Do i need any other pip install?

test_regular_client.py ran fine in 0.2.3.

Thanks.

**Comment by joselpena75** [comment]
You have to create a config file with all your personal information, in json format with ACCOUNT_NUMBER, CLIENT_ID, REDIRECT_URI, JSON_PATH (for access and refresh token)
