### ISSUE TITLE
Get_option_chain

### ISSUE THREAD

**Issue by smsouthard** [areed1192/td-ameritrade-python-api#33]
get_options_chain method in TDClient class expects a dictionary, so the OptionChain object recommended to be used in the code isn't accepted unless you explicitly reference the query_parameters dictionary object.

Recommend EITHER updating the code comments to reflect this OR having the  get_options_chain method test for an OptionChain object and proceed accordingly. 

https://github.com/areed1192/td-ameritrade-python-api/blob/a3aabf2228eb615f579a5208fa2249f506f926a5/td/client.py#L910

**Comment by mLewisLogic** [comment]
++

This broke in the recent refactor.
Current workaround is:

```python
client.get_options_chain(OptionChain(...)._get_query_parameters())
```

**Comment by smsouthard** [comment]
Yes, I tried pointing that out but wasn't as clear as I could have been. Appreciate the assistance @mLewisLogic

**Comment by areed1192** [comment]
The comments have been updated.
