### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by roychen97** [areed1192/td-ameritrade-python-api#35]
ERROR: Could not find a version that satisfies the requirement td-ameritrade-python-api (from versions: none)
ERROR: No matching distribution found for td-ameritrade-python-api

not quite sure if it's only me, I can install other packages like tensorflow normally though

**Comment by areed1192** [comment]
That's odd I don't have that issue on my end. I'm assuming that you're running the command like so:

```console
pip install td-ameritrade-python-api
```

**Comment by Kreationz79** [comment]
Worked fine for me.

**Comment by lobstaboy** [comment]
I'm having the same issue:

ERROR: Could not find a version that satisfies the requirement td-ameritrade-python-api (from versions: none)
ERROR: No matching distribution found for td-ameritrade-python-api

I tried it from the command line. I have also installed other packages recently.

**Comment by areed1192** [comment]
@lobstaboy Could you give me some details about the version of Python you have installed and some of your platform specifications?

**Comment by pennedav** [comment]
I'm getting the same issue, platform info below. pip is installed initially from Ubuntu packages, but then upgraded via pip3 --upgrade. I've had no issue installing other things via pip3 like aws-cli utilities. Hope this helps.

```
~$ pip3 install td-ameritrade-python-api
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement td-ameritrade-python-api (from versions: none)
ERROR: No matching distribution found for td-ameritrade-python-api
~$ pip3 --version
pip 20.1.1 from /home/dmp2226/.local/lib/python3.5/site-packages/pip (python 3.5)
~$ python3 --version
Python 3.5.2
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
~$
```

**Comment by areed1192** [comment]
That’s the exact reason you’re having the issue. You need python 3.7 or higher in order to use the library.

**Comment by pennedav** [comment]
Yeah, my bad for not paying attention to the version requirements :)

I expect that's the issue for the other folks as well.

**Comment by lobstaboy** [comment]
I upgraded to 3.7 and it worked as well! Was having a little bit of a problem with VS Code, it was not importing from the config file, took me a while to figure this out, but going to File --> Close Folder, then opening up the file again worked. Closing out of VS Code completely did not fix it, kind of strange.

**Comment by spitzbubchen** [comment]
Is there a particular reason that this api is not compatible with python 3.6? Most linux distributions come with python < 3.7 installed so this is annoying and requires extra effort on the part of the user. Can the requirements be relaxed to allow python >= 3.6?
