### ISSUE TITLE
__init__() got an unexpected keyword argument 'consumer_id'

### ISSUE THREAD

**Issue by msmith6307** [areed1192/td-ameritrade-python-api#37]
I received the below error when trying to use the usage example code

``# Import the client
from td.client import TDClient

# Create a new session, credentials path is optional.
TDSession = TDClient(
    account_number='ACCOUNT_NUMBER',
    consumer_id='CONSUMER_ID',
    redirect_uri='REDIRECT_URI'
)

# Login to the session
TDSession.login()

# Grab real-time quotes for 'MSFT' (Microsoft)
msft_quotes = TDSession.get_quotes(instruments='MSFT')``

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-b72cd98b7af6> in <module>
      9 # )
     10 
---> 11 TDSession = TDClient(
     12     account_number='ACCOUNT_NUMBER',
     13     consumer_id='CONSUMER_ID',

TypeError: __init__() got an unexpected keyword argument 'consumer_id'

**Comment by speculator9** [comment]
I believe that it is because in the latest versions the consumer_id attribute has be replaced with client_id. There are sample files on the repository which would be helpful to you.

**Comment by msmith6307** [comment]
That was it. Thanks
