### ISSUE TITLE
modify_order function missing JSON conversion, same as Issue #38

### ISSUE THREAD

**Issue by eyesuk** [areed1192/td-ameritrade-python-api#41]
HI!,
Hope you and everyone in your family is well.  As @anontrader pointed out in issue #38, the following code is also missing within the order modification function.  Placing the code below in line 1796 of the client.py allowed me to modify existing orders.

```
        if isinstance(order, Order):
            order = order._saved_order_to_json()
            order = json.loads(order)                                    
        else:
            order = order
```
Thanks for all your help!

**Comment by areed1192** [comment]
Was addressed in #46
