### ISSUE TITLE
async ouch

### ISSUE THREAD

**Issue by ethanj** [areed1192/td-ameritrade-python-api#42]
Hi Alex.

Spent the last few hours tracking down what I think is a bug.

`stream()` at 
https://github.com/areed1192/td-ameritrade-python-api/blob/master/samples/api_streaming.py#L78
ends up passing `pipeline_start=False` to `_connect` at
https://github.com/areed1192/td-ameritrade-python-api/blob/master/td/stream.py#L533

The problem is that `stream()` sends the subsequent data commands without waiting for the connect to finish.
On my machine, I end up with the commands being received out of order, leading to an error/disconnect.

```
Connection established. Streaming will begin shortly.
====================
Message Recieved:

{'response': [{'service': 'LEVELONE_FUTURES', 'requestid': '1', 'command': 'SUBS', 'timestamp': 1591951833155, 'content': {'code': 3, 'msg': 'Login Denied. - Please login first.'}}]}
--------------------

====================
Message Recieved:

{'response': [{'service': 'ADMIN', 'requestid': '0', 'command': 'LOGIN', 'timestamp': 1591951833155, 'content': {'code': 0, 'msg': '05-2'}}]}
--------------------

Connection with server closed, beginning close process...
Event loop was not closed.
```

It's unclear to me why you even have that `pipeline_start` arg, so I did not try to submit a fix, but by just always waiting for the login command, it now works for me.

uggg

PS `Recieved` is spelled wrong :)

Ethan

**Comment by areed1192** [comment]
Thanks for pointing this out, it's a strange bug that seems to be isolated to only a specific group of people from what I can tell. The way I wrote the code, it's supposed to wait for the login request to be made before doing anything else.

For whatever, reason that doesn't seem to be happening. Could you help me out a little bit and let me know if you're on **Mac or Windows**?

**Comment by ethanj** [comment]
I am on Mac

**Comment by areed1192** [comment]
Okay, I suspected that. For whatever reason, the issue seems to only be prevalent on Macs from what I can tell. I can take a look into it and see if there is an easy fix for it.

**Comment by tmatrixhy** [comment]
I'm receiving this same bug on a raspberry pi. It happens once a day at least (at random times).

I am receiving Level One Futures (8 tickers) and Level One Quotes (10 tickers). 

Wanted to say thank you for this API as well. The documentation from TDA is so so so bad!

**Comment by areed1192** [comment]
Yeah, I don't know if there is a real fix I can issue that will easily fix the issue. It might be better on your end to actually, check if the connection is closed and if it is, then reconnect.

I'll start looking into adding a "reconnect" method into the library and hopefully make the process a little less painful. Let me know your thoughts.

**Comment by tmatrixhy** [comment]
> I'll start looking into adding a "reconnect" method into the library and hopefully make the process a little less painful. 

This is exactly what I was going to do. Its hacky but I don't think there's a way around it honestly. Even if you find a way to resolve it, its easier for me (personally) to just run two separate instances of my current streaming setup and have the database verify the (missing) inputs from one or the other.

You're doing great work here :). Thanks again!

**Comment by ethanj** [comment]
Why not have stream be a pipeline that just prints on the callback?
