### ISSUE TITLE
td/client.py -> update_watchlist bug

### ISSUE THREAD

**Issue by DurFactor** [areed1192/td-ameritrade-python-api#43]
Tried to run a method (update_watchlist) that passes a Patch request, found a bug with the way the request is generated. In line 484 I updated “data=data” to “json=data”. This update resolved the issue for me.

Shoutout to you @areed1192 for taking the time to provide a great library!

**Comment by eyesuk** [comment]
@DurFactor 
Are you referencing this line?
```
elif method == 'patch':
            response = requests.patch(url=url, headers=headers, params=params, data=data, json=json, verify=True)
```

Also can you please provide an example of how you are updating the watchlist?  I have been fighting all weekend with it and getting an "Unsupported Media Type error". 

Thanks for your help man

**Comment by DurFactor** [comment]
@eyesuk 
I was initially referencing line 484 but that was incorrect (mobile browser troubles). Sorry for the confusion. The last line in the update_watchlist method needs to be updated to pass the payload as json and not as data.

Update the line from:
"return self._make_request(method='patch', endpoint=endpoint, data=payload)" to
"return self._make_request(method='patch', endpoint=endpoint, json=payload)"

        # define the payload
        payload = {
            "name": name,
            "watchlistId": watchlist_id,
            "watchlistItems": watchlistItems
        }

        # define the endpoint
        endpoint = 'accounts/{}/watchlists/{}'.format(account, watchlist_id)

        # make the request
        return self._make_request(method='patch', endpoint=endpoint, json=payload)

As for updating the watchlist, I provided an example that checks length, removes all but 1 item, then updates accordingly. You may be able to achieve the same by updating the watchlist with a single sequenceId but I haven't really played around with the idea yet.

Example:

```
symbolsFormatted = []
symbolsDelete = []

# The reason I iterate and call out the sequenceId here is so that the 1 remaining item in the list will always be overwritten. Otherwise you could keep the sequenceId at 0
for i in symbolList:
    symbolsFormatted.append({"sequenceId": symbolList.index(i)+1, "instrument":{"symbol": i}})

TDSession.login()

obj = TDSession.get_watchlist(account=ACCOUNT_NUMBER,watchlist_id=wlId)
for i in range(1, len(obj['watchlistItems'])):
    symbolsDelete.append({"sequenceId": i})

# Remove all but 1 items
TDSession.update_watchlist(account=ACCOUNT_NUMBER, watchlist_id=wlId, name=name, watchlistItems=symbolsDelete)

# Update with new symbols
TDSession.update_watchlist(account=ACCOUNT_NUMBER, watchlist_id=wlId, name=name, watchlistItems=symbolsFormatted)

TDSession.logout()
```

Hope that helps!

**Comment by eyesuk** [comment]
Thank you for your time and code man!
I appreciate it I'll try it today.

Hope you and your loved ones are safe bro!
