### ISSUE TITLE
create_saved_order bug

### ISSUE THREAD

**Issue by shengjia2020** [areed1192/td-ameritrade-python-api#44]
In client.py -> create_saved_order function, the following lines have typo:

# check to see if it's an order object.
        if isinstance(saved_order, Order):
            order = order._saved_order_to_json()
        else:
            order = order

which need to be changed to:

# check to see if it's an order object.
        if isinstance(saved_order, Order):
            order = saved_order._saved_order_to_json()
        else:
            order = saved_order

**Comment by areed1192** [comment]
Should be fixed.
