### ISSUE TITLE
Bug in place_order

### ISSUE THREAD

**Issue by westofpluto** [areed1192/td-ameritrade-python-api#46]
The existing client.place_order function has a bug that makes it return a 400 bad request error. The issue is that the JSON payload for this order is being sent in the 'json' variable in self._make_request(). It looks like the function will only work if instead you send the data in the 'data' field.

I fixed this temporarily in my code by creating a client class that extends TDClient and overrides the place_order function to do this correctly. My class looks like this:

    class CustomTDClient(TDClient):
        def place_order(self, account: str, order: dict) -> dict:
            print("In CustomTDClient place_order")
            # check to see if it's an order object.
            if isinstance(order, Order):
                order = order._saved_order_to_json()
            else:
                order = order

            # make the request
            endpoint = 'accounts/{}/orders'.format(account)
            return self._make_request(method='post', endpoint=endpoint, mode='json', data=order, order_details=True)
    
You probably want to fix this in the repo code.

**Comment by eyesuk** [comment]
Issue already identified in #38 and #41. 

Please consider deleting in order to reduce duplicate issue and speed up bug fixes

**Comment by areed1192** [comment]
This issue should be fixed now. If you could please verify it that would be helpful.

**Comment by eyesuk** [comment]
@areed1192 The code change works!

Thanks for your help and this awesome API, I appreciate you bro!

**Comment by areed1192** [comment]
Perfect, I'll be closing this issue then.
