### ISSUE TITLE
Missing Streaming Quotes

### ISSUE THREAD

**Issue by baomx888** [areed1192/td-ameritrade-python-api#47]
I did a subscription from TD for dow 30 stocks.  I noticed only a small portion of streaming data is provided. I got the data stream every second, But most field is NaN and the volume is not continuos as well.  Is that normal for everyone?

**Comment by areed1192** [comment]
The streaming endpoint will only return data as it changes. If the data doesn't change then, it won't send anything back. That's just how the API was built. Additionally, don't be surprised if you find specific instruments behave differently than other ones, I have experienced that on my end as well.
