### ISSUE TITLE
What is the value of self.library_directory in the defaults.py?

### ISSUE THREAD

**Issue by jeffhu1** [areed1192/td-ameritrade-python-api#49]
In the StatePath class, we have that
```
def __init__(self, credentials_file: str = None):

        """Initalizes the StatePath Class"""        
        self.python_version = sys.version_info
        self.credenitals_file_name = 'td_state.json'
        self.settings_location = {}

        if credentials_file and isinstance(credentials_file, str):
            self.credentials_file: pathlib.Path = pathlib.Path(credentials_file)
        else:
            self.credentials_file: pathlib.Path = self.library_directory
```

https://github.com/areed1192/td-ameritrade-python-api/commit/32c9b61cae2d207eef21cd5abc954c01e5f25f0b#diff-e03670d854f5b6539e3fe0b8e7c84c82R31

What is the value of self.library_directory? Is it inherited from the parent path class?

**Comment by areed1192** [comment]
It would be the `td` folder. For example on my system it would look like the following:

```console
C:\Users\Alex\td-ameritrade-python-api\td
```

**Comment by jeffhu1** [comment]
Gotcha. I'm curious where it is defined in the case when the credentials file is none: 

https://imgur.com/a/XSOwKQQ

**Comment by jeffhu1** [comment]
Nevermind, I see that there is a property defined on line 54
