### ISSUE TITLE
Error when trying to use create_saved_order

### ISSUE THREAD

**Issue by msmith6307** [areed1192/td-ameritrade-python-api#50]
I am trying to use create_saved_order to debug my app since can't paper trade.  When I use below
```
limit_order = {
    "orderType": "LIMIT",
    "session": "NORMAL",
    "duration": "DAY",
    "price": 20.00,
    "orderStrategyType": "SINGLE",
    "orderLegCollection": [
      {
        "instruction": "SELL",
        "quantity": 1,
        "instrument": {
          "symbol": "AA",
          "assetType": "EQUITY"
        }
      }
    ]
}
new_order_response = td_client.create_saved_order(account=TD_ACCOUNT, saved_order=limit_order)
```
receive: UnboundLocalError: local variable 'order' referenced before assignment

but if I use 
`new_order_response = td_client.place_order(account=TD_ACCOUNT, order=limit_order) `
everything works as expected.

**Comment by areed1192** [comment]
I think you might be using an old version of the library. If you update it to the following:

```console
pip install td-ameritrade-python-api==0.2.8
```

you should be good. However, let me know once you update it.

**Comment by msmith6307** [comment]
Thanks update corrected the problem.
