### ISSUE TITLE
IsADirectoryError with or without credentials_path supplied

### ISSUE THREAD

**Issue by ner0tic** [areed1192/td-ameritrade-python-api#51]
```
Traceback (most recent call last):
  File "Ameritrade.py", line 96, in <module>
    account_number=args.acct_number)
  File "/home/pi/.local/lib/python3.7/site-packages/td/client.py", line 119, in __init__
    self._state_manager('init')
  File "/home/pi/.local/lib/python3.7/site-packages/td/client.py", line 207, in _state_manager
    with open(file=credentials_file_path, mode='r') as json_file:
IsADirectoryError: [Errno 21] Is a directory: '/home/pi/.local/lib/python3.7/site-packages/td'
```
I only just started to debug it, but not matter if I pass a credential file path or not to the Client instance I receive this error.  
I can see in `defaults.py` the `StatePath` class initiates by taking an optional path but the filename itelsef is hardcoded, but I could not follow where it ever gets concatted to the path when being opened for reading on line 207 of `client.py`

I am running on 4hours of sleep so I could jsut be missing a step somewhere.  I do have valid access and refresh tokens when tried on the td dev api site.

my code is simple at this point - I'm just starting to play with this module (library.)
```
if __name__ == '__main__':
    try:
        # start
        start_time = datetime.now()
        
        args = get_arguments()
 
        TDSession = TDClient(
          client_id=args.consumer_id,
          redirect_uri=args.redirect_url,
          account_number=args.acct_number)

        TDSession.login()


# end
        finish_time = datetime.now()
        logger.debug(finish_time)
        logger.debug(
          'Execution time: {time}'.format(
            time=(finish_time - start_time)))
        logger.debug("#"*20 + " END EXECUTION " + "#"*20)

        # bye
        sys.exit(0)
```
my args are read using the `configargparse` module and is being used the same way in other working projects.  I have verified the config values are correctly being read in.
I have tried it while also not supplying the account_number as in my code above for the sake of rounding it out.

**Comment by ner0tic** [comment]
I made 2 quick changes and the auth script kicked in finally.
They were in the `client.py` file:
after line 202 I add
```
credentials_file_path.joinpath(credentials_file.credenitals_file_name)
```
I then created a blank file matching the hardcoded filename in the `defaults.py` file which was `ts_state.json`  this was so I only had to modify one file.

**Comment by areed1192** [comment]
I'm going to modify your change to the following:

```python
# If it's a directory, then create the JSON setting path.
if credentials_file.is_dir:
    credentials_file_path = credentials_file.json_library_path()
else:
    credentials_file_path = credentials_file.credentials_file.absolute()
```

The assumption is if you don't provide anything related to a file path then I'll just be using the default setting folders. This way we only need to modify the `client.py` file.

**Comment by ner0tic** [comment]
That makes sense, I hadn't looked through the existing methods. I'm also not sure where I got the different state file name from and why I felt the need to modify that in my half conscious state.. But works great and I appreciate your work.
