### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by jdevito18** [areed1192/td-ameritrade-python-api#53]
When trying to install using pip I get the following message:
 Could not find a version that satisfies the requirement td-ameritrade-python-api==0.2.8 (from versions: )
No matching distribution found for td-ameritrade-python-api==0.2.8

Not sure if this is because I am on a mac or not.

**Comment by areed1192** [comment]
Are you installing it from PyPI? It looks fine from what I can tell.
