### ISSUE TITLE
TDAmeritrade Python API having small Tech indicator

### ISSUE THREAD

**Issue by shobnaren** [areed1192/td-ameritrade-python-api#54]
Do we have API for:
1) VWAP
2) ATR
3) Bband

**Comment by eyesuk** [comment]
Those are studies...

**Comment by areed1192** [comment]
No indicators are not part of this library. I do have another library that I am incorporating indicators that you can use with data returned from the API. Here is the link: [python-trading-robot](https://github.com/areed1192/python-trading-robot)
