### ISSUE TITLE
Default _token_validation nseconds = 5 is not enough

### ISSUE THREAD

**Issue by Aspire1Inspire2** [areed1192/td-ameritrade-python-api#56]
There might be situations like:

1. User's system time is not in perfect sync with TD Ameritrade system time.

2. User's network has unpredictable delay

When requesting, the unfreshed access token is not throwing out ```EXCEPTION```. It is just printing the following message:
```
================================================================================
RESPONSE STATUS CODE: 401
RESPONSE URL: https://api.tdameritrade.com/v1/marketdata/chains?symbol=MSFT
RESPONSE HEADERS: {'Date': 'Sat, 04 Jul 2020 15:18:02 GMT', 'Content-Type': 'application/json', 'Content-Length': '108', 'Connection': 'keep-alive', 'WWW-Authenticate': 'Bearer realm="null",error="invalid_token",error_description="keymanagement.service.access_token_expired: Access Token expired"', 'Cache-Control': 'no-cache,no-store,must-revalidate', 'Access-Control-Allow-Origin': '', 'Access-Control-Allow-Headers': 'origin, x-requested-with, accept, authorization, content-type', 'Access-Control-Max-Age': '3628800', 'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE, OPTIONS, HEAD, PATCH', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains, max-age=31536000'}
RESPONSE PARAMS: {}
RESPONSE TEXT: 
          {
        "error":"The access token being passed has expired or is invalid."
      		}
          
--------------------------------------------------------------------------------
```

Without throwing out refresh token expiration ```EXCEPTION```, user cannot try and catch it and the code will fail in downstream data extraction steps.

Suggestion:

1. increase the nseconds default in the _token_validation method to something like 60.
2. Throw ```EXCEPTION``` for response code 401 so the user can catch it and refresh the token himself/herself and post the request again. This would dramatically improve code robusticity.
3. Change the comparison criteria in _token_seconds method to also allow 60 seconds safe margin.

I created Pull request #57 to resolve this issue.

**Comment by areed1192** [comment]
Thanks for the fix, it's been merged to the repo. Going to close this issue now.
