### ISSUE TITLE
Can data of level2 total view be saved?

### ISSUE THREAD

**Issue by jzhan6** [areed1192/td-ameritrade-python-api#58]
Hi 

I tried to run TDStreamingClient.level_two_total_view
But somehow data were not be saved to the csv file.  I used the following scripts,
TDStreamingClient.write_behavior(
    write='csv',
    file_path=r"./raw_data_20200709_apple.csv", 
    append_mode=True
)
TDStreamingClient.level_two_total_view(symbols = ['AAPL'], fields = [0,1,2])
TDStreamingClient.stream(print_to_console=False)
await TDStreamingClient.build_pipeline()

And is it possible to save the output of level_two_total_view to a python variable instead writing it to a csv file?

**Comment by areed1192** [comment]
Yes if you look at the [stream example](https://github.com/areed1192/td-ameritrade-python-api/blob/master/samples/api_streaming.py), you'll see how to grab it in the script.

**Comment by freephys** [comment]
Following the stream example but get an error while regular operations such as get historical price etc worked. It is appreciated to get some help on solving it. Thanks
https://github.com/areed1192/td-ameritrade-python-api/issues/72

**Comment by agrieco** [comment]
Having the same issue here.

**Comment by ckreske** [comment]
I have the same issue as freephys.
