### ISSUE TITLE
problem with place_order when passing <order>

### ISSUE THREAD

**Issue by gsimanju** [areed1192/td-ameritrade-python-api#6]
When I created the order class and its order leg, then try to call place_order, I get TypeError: Object of type Order is not JSON serializable

It seems the order leg is stored as object in the order which json refuses to dump. Am I thinking this correctly?

CODE:
new_order = Order()
new_order.order_session(session=ORDER_SESSION.NORMAL)
new_order.order_duration(duration=DURATION.DAY)
new_order.order_type(order_type=ORDER_TYPE.LIMIT)
new_order.order_strategy_type(order_strategy_type=ORDER_STRATEGY_TYPE.SINGLE)

new_order_leg = OrderLeg()
new_order_leg.order_leg_instruction(instruction=ORDER_INSTRUCTIONS.BUY)
new_order_leg.order_leg_price(price=100.0)
new_order_leg.order_leg_quantity(quantity=1)
new_order_leg.order_leg_asset(asset_type=ORDER_ASSET_TYPE.EQUITY, symbol='MSFT')

# add to new_order
new_order.add_order_leg(order_leg=new_order_leg)
# pprint prints fine
pprint.pprint(new_order._grab_order())
print('-'*80)

# submit order
order_result = TDSession.place_order(account = ACCOUNT_NUMBER, order = new_order)

the place_order returns TypeError: Object of type Order is not JSON serializable

**Comment by gsimanju** [comment]
I'm sure this is not the correct long term solution, but if I add "order = order._saved_order_to_json()" before the request.post, then it works.

I found a workaround, which I'm not sure is the proper way of doing it.
If i change the json.dump to _saved_order_to_json() then it works

WAS:
# make the request
response = requests.post(
            url=url, headers=merged_headers, data=json.dumps(order),  verify=True)


IS:
# make the request
response = requests.post(
            url=url, headers=merged_headers, data=order._saved_order_to_json(), verify=True)

**Comment by areed1192** [comment]
Hi there,

I took a look at the issue and it appears, I had accidentally removed a portion that would check if the argument passed through was `td.Order` object. I fixed it, so you should be able to either pass through a dictionary object or a `td.Order` object.
