### ISSUE TITLE
How to create watchlist and get watchlists.

### ISSUE THREAD

**Issue by SunHxiao** [areed1192/td-ameritrade-python-api#61]
Hello, Everyone.
I am very interested in TD Ameritrade python API.
So I would like to learn this API in detail.
When I create a watchlist, I have some issues.
I don't know how to make watchlist items.
Would you please kindly inform me about it with sample data?
I would like to create a new watchlist with it.
Thank you very much!
I will wait for your favorable reply.
Best regards!

**Comment by areed1192** [comment]
You need to pass through a dictionary object that looks something like the following:

```json
{
    "name": "my_watchlist",
    "watchlistItems": [
        {
            "quantity": 1,
            "averagePrice": 10.00,
            "commission": 0,
            "purchasedDate": "2020-07-01",
            "instrument": {
                "symbol": "AA",
                "assetType": "EQUITY" 
            }
        }
    ]
}
```

Then using the library you would pass it through like so,

```python
my_items =  [
    {
        "quantity": 1,
        "averagePrice": 10.00,
        "commission": 0,
        "purchasedDate": "2020-07-01",
        "instrument": {
            "symbol": "AA",
            "assetType": "EQUITY" 
        }
    }
 ]

td_client.create_watchlist(
    account = 'MyAccountNumber', 
    name = 'MyWatchlistName', 
    watchlistItems = my_items
)
```

**Comment by SunHxiao** [comment]
COOL.
Thank you very much!

**Comment by areed1192** [comment]
You could just create a new instance of the `td_client` for each user when they login.

**Comment by SunHxiao** [comment]
Would you please teach me the example?
Thank you very much!
