### ISSUE TITLE
get_market_hours not working

### ISSUE THREAD

**Issue by spitzbubchen** [areed1192/td-ameritrade-python-api#62]
The following:

`TDSession.get_market_hours(markets = ['EQUITY'], date = '2019-10-19')`

leads to this error:

`RESPONSE TEXT: {"timestamp":"2020-07-12","status":400,"error":"Bad Request","message":"Input date is not acceptable.","path":"/markethours-v1/markets/"}`

**Comment by areed1192** [comment]
It's because it's a historical date, you can only use the current day and after.

**Comment by spitzbubchen** [comment]
Okay, got it! Wasn't clear from the TD API documentation: 

> The date for which market hours information is requested. Valid ISO-8601 formats are : yyyy-MM-dd and yyyy-MM-dd'T'HH:mm:ssz.
