### ISSUE TITLE
Permssion error for TD

### ISSUE THREAD

**Issue by jkerivan** [areed1192/td-ameritrade-python-api#65]
Hi, I am seeing the following error on multiple machines and am not sure why?  I am running on a windows machine.

CDmarco-gRPm7x1S\lib\site-packages\td\client.py", line 119, in __init__
    self._state_manager('init')
  File "C:\Users\james\.virtualenvs\MACDmarco-gRPm7x1S\lib\site-packages\td\client.py", line 207, in _state_manager
    with open(file=credentials_file_path, mode='r') as json_file:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\james\\.virtualenvs\\MACDmarco-gRPm7x1S\\lib\\site-packages\\td'

**Comment by areed1192** [comment]
It looks like the file might be open, and because of that, it can't read it. That would be my first guess.

**Comment by jkerivan** [comment]
I am seeing it on multiple machines and I have been sure to close everything but the cmd and run.  Still seeing it

**Comment by amazzuca** [comment]
> Hi, I am seeing the following error on multiple machines and am not sure why? I am running on a windows machine.
> 
> CDmarco-gRPm7x1S\lib\site-packages\td\client.py", line 119, in **init**
> self._state_manager('init')
> File "C:\Users\james.virtualenvs\MACDmarco-gRPm7x1S\lib\site-packages\td\client.py", line 207, in _state_manager
> with open(file=credentials_file_path, mode='r') as json_file:
> PermissionError: [Errno 13] Permission denied: 'C:\Users\james\.virtualenvs\MACDmarco-gRPm7x1S\lib\site-packages\td'

It happens the same to me. Windows10, anaconda, spyder.

**Comment by areed1192** [comment]
Random question, are you both using `Spyder`?

**Comment by jkerivan** [comment]
No, on windows tho.

**Comment by amazzuca** [comment]
Maybe it has to do with using a virtual environment? It seems that there is other file using the file simultaneously.

**Comment by areed1192** [comment]
Have you guys learned anything else about this issue?

**Comment by amazzuca** [comment]
No, I couldn't figure out what could be the reason. I left the project on stand-by.
