### ISSUE TITLE
ERROR: You don't have permission to access this resource.

### ISSUE THREAD

**Issue by andymingxinsun** [areed1192/td-ameritrade-python-api#69]
Hi Alex,

First of all, I want to say thank you for your work on creating this python api for TD Ameritade.
I am working to build a python trading bot. As of now, I am facing an issue where  TD API respond "You don't have permission to access this resource." on TDSession.place_order(account,td_order)

I have all access_token, refresh_token setup in TdAmeritradeState.json, and initialized them when TDSession was constructed. I also have auth my bot to get access to my TD account. However, looks like when place_order() get called, it did not pick access_token. As a result, i got this "You don't have permission to access this resource." response from TD api.

Would you give me some hint or code example on how to fix this issue? I am new to Python. Anything is greatly appreciated. Thanks

Andy

**Comment by andymingxinsun** [comment]
Here is how i created my order and order_leg object

        td_order = Order()
        td_order_leg = OrderLeg()
        td_order.order_session(session=td_enums.ORDER_SESSION.NORMAL)
        td_order.order_duration(duration=td_enums.DURATION.GOOD_TILL_CANCEL)
        td_order.order_type(order_type=td_enums.ORDER_TYPE.LIMIT)
        td_order_leg.order_leg_instruction(instruction=td_enums.ORDER_INSTRUCTIONS.BUY_TO_OPEN)
        td_order_leg.order_leg_price(price=2.00)
        td_order_leg.order_leg_quantity(quantity=1)
        td_order_leg.order_leg_asset(asset_type=td_enums.ORDER_ASSET_TYPE.OPTION, symbol='AAPL_071720C400')
        td_order.add_order_leg(order_leg=td_order_leg)

**Comment by areed1192** [comment]
How are you submitting the order? That particular error happens when you're trying to access an account that your access token isn't tied to.

**Comment by andymingxinsun** [comment]
Hi Alex,

Thank you for you reply. After more reading on you code and some tries and fails, I have solved the ERROR - "You don't have permission to access this resource."
I am still having issues with create a proper Order instance and pass it to place_order function. As of now, I saved my Order information directly into a dictionary and pass it to  place_order function as a workaround, just like the way you showed in your youtube channel video. 

During my tries and fails, i saw the following ERROR. 

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.tdameritrade.com', port=443): Max retries exceeded with url:

Does this ERROR happen because of the same webservice call occurred multiple times in a short period of time? Do you know if TD api has any limitation on number of webservice calls per second/minute? Is this limitation tied to clientID or access_token? Again, thank you so much for you time.

Andy

**Comment by areed1192** [comment]
That error could be caused by multiple things, but it sounds like the request timed out. There is a rate limit of 120 calls per minute, so if you exceed that it'll kick you back. What request does this happen with?

**Comment by andymingxinsun** [comment]
Hi Alex,

Thanks for replying back to me. Looks like it happened because I did not add this _do_init = True, when i initialize new session by calling TDClient(). As a result, it keep calling TD to refresh my tokens, whenever i tried to initialize new session

Andy

**Comment by areed1192** [comment]
Interesting, so you had to explicitly set `_do_init` to `True`? The only reason I ask is that it's set to `True` by default.

**Comment by andymingxinsun** [comment]
Yes, this is how i initialize my session
TdSession = TDClient(
        client_id = CONSUMER_ID,
        redirect_uri = REDIRECT_URI,
        credentials_path = CREDENTIALS_PATH,
        account_number = ACCOUNT_NUMBER,
        _do_init = True)
