### ISSUE TITLE
{'error': 'A validation error occurred while processing the request.'}

### ISSUE THREAD

**Issue by gsimanju** [areed1192/td-ameritrade-python-api#7]
I tried submitting a new place_order but I always get code 400 error. Do you know what minimum information I need to pass for a LIMIT order?

new_order = Order()
new_order.order_session(session=ORDER_SESSION.NORMAL)
new_order.order_duration(duration=DURATION.DAY)
new_order.order_type(order_type=ORDER_TYPE.LIMIT)
new_order.order_strategy_type(order_strategy_type=ORDER_STRATEGY_TYPE.SINGLE)
new_order.complex_order_type(complex_order_strategy_type=COMPLEX_ORDER_STRATEGY_TYPE.NONE)
new_order.order_price(price=200.00)

new_order_leg = OrderLeg()
new_order_leg.order_leg_instruction(instruction=ORDER_INSTRUCTIONS.BUY)
new_order_leg.order_leg_quantity(quantity=1)
new_order_leg.order_leg_asset(asset_type=ORDER_ASSET_TYPE.EQUITY, symbol="AAPL")
new_order.add_order_leg(order_leg=new_order_leg)

order_result = TDSession.place_order(account = ACCOUNT_NUMBER, order = new_order)`

**Comment by areed1192** [comment]
Sounds like you got it figured it out from the email you sent. I'm going to close this issue and then modify the TD files.

**Comment by eyesuk** [comment]
HI!
Sorry to bug in this old thread, can you please provide insight into what gsimanju did to fix it?  I am going crazy trying to figure out where I am going wrong here.

Thanks for your help
