### ISSUE TITLE
Unable to query ChildOrderStrategies[n] status

### ISSUE THREAD

**Issue by eyesuk** [areed1192/td-ameritrade-python-api#70]
Hello Alex,
I am unsure if the is a limitation with the API or not, but at the moment I am unable to get child order status using get_orders_path.  I have been submitting orders with childorderStrategies, and I have been running into issues identifying the order status of the childorders when multiple activity for the same equity exist in the same day.

Is there a way to retrieve childorders with the 'QUEUED' status?

Thanks for your help man!
Hope you and your loved ones are safe.

**Comment by areed1192** [comment]
No, you can't query on Child Orders to my knowledge. When you use the query functionality it only returns the parent order at unless the child executed in which case it is considered its own order.

**Comment by eyesuk** [comment]
Thanks boss! 👍🏾👍🏾
