### ISSUE TITLE
modify_order() missing order object check similar to issue 38 

### ISSUE THREAD

**Issue by eyesuk** [areed1192/td-ameritrade-python-api#71]
Hello Alex,
It appears that in the client.py, function modify_order() is missing the order object check found in the place_order() function. This is causing an json error while trying to modify an order. This is similar to issue 38

Missing code:

```  
if isinstance(order, Order):
    order = order._grab_order()
else:
     order = order
```

Thanks man

**Comment by areed1192** [comment]
Thanks for pointing this out, I fixed it in the repo and will push it out in the next update. Thanks for the help :)
