### ISSUE TITLE
stream-api error 

### ISSUE THREAD

**Issue by freephys** [areed1192/td-ameritrade-python-api#72]
Try to get streaming working following
https://github.com/areed1192/td-ameritrade-python-api/blob/master/samples/api_streaming.py

I checked TDStreamingClient.data_requests['requests'], that has the  'command': 'SUBS' etc. 

Connection established. Streaming will begin shortly.
====================
Message Received:

After a few heartbeat messages , then get the error message

Message Received:

{'notify': [{'service': 'ADMIN', 'timestamp': XXX, 'content': {'code': 30, 'msg': 'Stop streaming due to empty subscription'}}]}

Try in both regular hours or after hours, always get similar error message. Please help to make the streaming api working  

Thanks

**Comment by ckreske** [comment]
Hey freephys did you ever solve this issue? I am experiencing the same problem.
