### ISSUE TITLE
GET Transaction History gives 403 Error Response

### ISSUE THREAD

**Issue by sherodkeen** [areed1192/td-ameritrade-python-api#73]
I'm hoping to grab my transaction history, but I'm getting a 403 response. I have gone through the authentication process and it downloaded the credentials file containing the access_token, refresh_token, etc. 

I noticed the Response Url has "none" instead of the account number. Could that be the issue or is it something else?

RESPONSE STATUS CODE: 403
RESPONSE URL: https://api.tdameritrade.com/v1//accounts/None/transactions?type=ALL&startDate=2019-08-01&endDate=2020-07-30
RESPONSE HEADERS: {'Date': 'Sat, 18 Jul 2020 14:59:43 GMT', 'Content-Type': 'application/json', 'Content-Length': '68', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'X-API-Version': '1.2.8', 'Access-Control-Allow-Origin': '', 'Access-Control-Allow-Headers': 'origin, x-requested-with, accept, authorization, content-type', 'Access-Control-Max-Age': '3628800', 'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE, OPTIONS, HEAD, PATCH', 'Content-Security-Policy': "frame-ancestors 'self'", 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains, max-age=31536000'}
RESPONSE PARAMS: {}
RESPONSE TEXT: {
  "error" : "You don't have permission to access this resource."
}

**Comment by areed1192** [comment]
Are you passing through your account number when you're initializing the `td_client`?

**Comment by sherodkeen** [comment]
No I hadn't. I was just using the below example from the "Usage" section of the page found at:
https://github.com/areed1192/td-ameritrade-python-api

I deleted the Credentials file, added in the  account_number='{placed account number here]', and went through the process again. It's still giving me a 403 and still has "None" in the response url.

Below is an example of how I added in the account_number

TDSession = TDClient(
    client_id='<CLIENT_ID>',
    redirect_uri='<REDIRECT_URI>',
    credentials_path='<PATH_TO_CREDENTIALS_FILE>',
    account_number='{I placed my account number here}'
)

**Comment by areed1192** [comment]
Gotcha, that's a bug in the code, it's not using the default account number in requests. For now, please explictitly pass through the account number when you make the call to the `get_transactions` method. Here is an example of what it would look like:

```python
td_client.get_transactions(
   account='123456789',
   transaction_type='ALL',
   start_date='2019-01-31',
   end_date = '2019-04-28'
)
```

That should fix the issue for you.

**Comment by sherodkeen** [comment]
@areed1192 Adding the account number to the get_transaction method worked. Thank you!
