### ISSUE TITLE
Option Chain won't work

### ISSUE THREAD

**Issue by LonginusHeart** [areed1192/td-ameritrade-python-api#75]
I can't seem to get option chain functionality working. If I pass in an option_chain object then the TDsession.get_options_chain call returns an error:

Error using parse>_coerce_args (line 120)
Python Error: TypeError: Cannot mix str and non-str arguments

If I instead pass in an identical dict I get:

BAD REQUEST - STATUS CODE: 400
RESPONSE URL: https://api.tdameritrade.com/v1/marketdata/chains?symbol=MSFT&contractType=CALL&optionType=S&fromDate=2020-08-01&toDate=2020-09-01&strikeCount=4.0&includeQuotes=FALSE&range=ALL&strategy=SINGLE
RESPONSE HEADERS: {'Date': 'Sun, 19 Jul 2020 02:09:48 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Application-Context': 'application:8080', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'nnCoection': 'close', 'Cache-Control': 'no-cache,no-store,must-revalidate', 'Access-Control-Allow-Origin': '', 'Access-Control-Allow-Headers': 'origin, x-requested-with, accept, authorization, content-type', 'Access-Control-Max-Age': '3628800', 'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE, OPTIONS, HEAD, PATCH', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains, max-age=31536000'}
RESPONSE PARAMS: {}
RESPONSE TEXT: {"error":"Bad request."}

**Comment by areed1192** [comment]
I think it's the `StrikeCount` that is throwing it off, when I remove that argument it seems to work fine.

**Comment by LonginusHeart** [comment]
That did it. Thank you!
