### ISSUE TITLE
Stop streaming due to empty subscription

### ISSUE THREAD

**Issue by ppkantorski** [areed1192/td-ameritrade-python-api#76]
So I got the API working.. but when I test TDStreamingClient.stream(), I get the following output.

```
TDStreamingClient.level_one_quotes(
       symbols=["SPY", "IVV", "SDS"], 
       fields=list(range(0, 50)) 
)
TDStreamingClient.stream()

Connection established. Streaming will begin shortly.
====================
Message Received:

{'response': [{'service': 'ADMIN', 'requestid': '0', 'command': 'LOGIN', 'timestamp': 1595453967759, 'content': {'code': 0, 'msg': '08-2'}}]}
--------------------

====================
Message Received:

{'notify': [{'heartbeat': '1595453978473'}]}
--------------------

====================
Message Received:

{'notify': [{'heartbeat': '1595453988490'}]}
--------------------

====================
Message Received:

{'notify': [{'service': 'ADMIN', 'timestamp': 1595453993677, 'content': {'code': 30, 'msg': 'Stop streaming due to empty subscription'}}]}
--------------------

Connection with server closed, beginning close process...
```

Kind of confused why this is happening.. everything is set up properly, my credentials.json is created, login states 'True'.  Any advice?

**Comment by eyesuk** [comment]
Do you the sample code? I can't get it to work for me?

**Comment by ppkantorski** [comment]
I was just trying to run the api_streaming.py function.. cant get it working.  however I did manage to get the api_pipeline.py function to work.  My only issue with it is that the data is not written to the .csv file until after the pipeline closes.  It would be nice if data is written as it comes in, trying to figure out how to do that at the moment.

**Comment by ckreske** [comment]
I have the same issue as op.

from td.client import TDClient
from config import *

# Create a new instance of the client
td_client = TDClient(
    client_id=CONSUMER_KEY,
    redirect_uri=REDIRECT_URI,
    credentials_path=JSON_PATH
)

# login to a new session
td_client.login()

def td_stream():
    # Create a streaming client
    td_stream_client =  td_client.create_streaming_session()
    # Specify the write behavior of the stream
    td_stream_client.write_behavior(
        write='csv',
        file_path='E:/Stock Data/stream_data.csv',
        append_mode=False
    )
    # level 1 quotes
    td_stream_client.level_one_quotes(symbols=['AAPL','MSFT'], fields=list(range(0, 38)))
    # Start Streaming
    td_stream_client.stream()
    return

td_stream()

**Comment by tarun14110** [comment]
I am also getting same error on running `api_streaming.py` sample.

**Comment by areed1192** [comment]
Hey Guys,

I just wanted to chime in here. Keep in mind that the `streaming_api` won't always return results. For example, any of the following conditions could cause an empty stream to happen:

1. There is no change in the data, the stream **only sends back data when there is a change in price**.
2. Most services only working during **regular market hours**, even for Forex and Futures.
3. After multiple empty responses, the stream will close whether you want it to or not. That's because TD will close it.

If these issues persist during regular market hours, then let me know.

**Comment by speck88** [comment]
I'm having the same issue with level one quotes during market hours

**Comment by ckreske** [comment]
Same. Tried during regular market hours. Tried MSFT and AAPL.

**Comment by areed1192** [comment]
Hey Guys,

I found the issue, there is a bug in the `stream.py` file if you go to the `async def _connect(self)` method there is causing the script to end up in an infinite loop. It currently looks like the following:

```python
        # Grab the login info.
        login_request = self._build_login_request()

        # Create a connection.
        self.connection = await websockets.client.connect(self.websocket_url)

        # check it before sending it back.
        if await self._check_connection() and pipeline_start == True:

            # Login to the stream.
            await self._send_message(login_request)
            await self._receive_message(return_value=True)
            return self.connection
        
        else:

            # Login to the stream.
            await self._send_message(login_request)

            # THIS WAS CAUSING THE ISSUE!
            await self._receive_message(return_value=False)
            return self.connection
```

When it should look like the following:

```python
        # Grab the login info.
        login_request = self._build_login_request()

        # Create a connection.
        self.connection = await websockets.client.connect(self.websocket_url)

        # See if we are connected.
        is_connected = await self._check_connection()

        # If we are connected then login.
        if is_connected:
            await self._send_message(login_request)
            return self.connection
```

I just pushed the fix to the master branch so you'll need to pull the changes again and this fix will be released in the next update

**Comment by speck88** [comment]
That got it to work for me. Thank you. I appreciate all of the work you have done.

**Comment by ckreske** [comment]
Looks like that fixed it! Thanks, Alex!
