### ISSUE TITLE
Typo in oauth.py /refresh endpoint handler

### ISSUE THREAD

**Issue by Enuratique** [areed1192/td-ameritrade-python-api#78]
https://github.com/areed1192/td-ameritrade-python-api/blob/ac7bdb1c3993150e394d4a28f32b539a4abded9a/td/oauth.py#L74

Looks like it should just be app.config['auth_client'].grab_refresh_token()

**Comment by areed1192** [comment]
Thanks for pointing this out, it's been fixed now. I'm going to be closing the issue now.
