### ISSUE TITLE
Completely and utterly broken

### ISSUE THREAD

**Issue by avisocan** [areed1192/td-ameritrade-python-api#80]
asdf

**Comment by areed1192** [comment]
Did you create a TD Developer account yet? Also, have you read the resources yet?

**Comment by avisocan** [comment]
Yes and yes. TD developer account, and the resources does not help in the slightest. Great. I have a key. Wonderful. My next step is to run this

TDSession = TDClient(
    client_id="the key from resources",
    redirect_uri='https://localhost/test',
    credentials_path=''
)
# Login to the session
TDSession.login()

# Create a streaming session
TDStreamingClient = TDSession.create_streaming_session()

**Comment by avisocan** [comment]
Deosnt work at all, as expected. Permission denied 
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\myusername\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\td'

**Comment by eyesuk** [comment]
Bro! You need to chill man, no need to be rude, especially if you want help.

**Comment by RossGlengarry** [comment]
You're being lazy, I started with no python knowledge at all and got this
working without aid using the resources Alex mentioned and provided.

I'm not saying it's easy, I'm saying it's possible, good luck.

**Comment by mtindall** [comment]
Agreed .. I don’t understand this line of thinking.. I’m trying to figure it out too but damn.. not how you win friends and influence people.
