### ISSUE TITLE
get_price_history  period and frequency str vs int

### ISSUE THREAD

**Issue by ckreske** [areed1192/td-ameritrade-python-api#82]
Hey Alex, 
I'm not sure if this is where I should post this, but I was trying to use the api to gather price history. However, I kept getting an 'Invalid Period.' I found out that you do not specify the argument type for period, but you do for frequency. I was typing in a string, when I should have used an integer. my fault.

`def get_price_history(self, symbol: str, period_type:str = None, period=None, start_date:str = None, end_date:str = None,
                          frequency_type: str = None, frequency: str = None, extended_hours: bool = True)` 

I then found out that if you try to run the line below you receive an error,

`TDSession.get_price_history('MSFT', period_type='day', period=1, frequency_type='minute', frequency='1')`

but if you switch the frequency to an int it works

`TDSession.get_price_history('MSFT', period_type='day', period=1, frequency_type='minute', frequency=1)`

I think it is because of this line in client.py

`if frequency_type == 'minute' and frequency not in [1, 5, 10, 15, 30]`

but if you run this,

`TDSession.get_price_history('MSFT', period_type='month', period=1, frequency_type='daily', frequency='1')`

all is good.

Is there a reason you specify str for frequency but require int when using minute as the frequency type? 
Sorry if this is a stupid question, I have only been using python for a few months. Still learning.

**Comment by areed1192** [comment]
No, that's my bad it should be consistent thank you for pointing this out. I'll address the issue and push it to the main branch and next update.
