### ISSUE TITLE
Third-party application may be attempting to make unauthorized access to your account._

### ISSUE THREAD

**Issue by NealWalters** [areed1192/td-ameritrade-python-api#83]
Using a URL like this (I changed the consumer id to post here): 
https://auth.tdameritrade.com/auth/?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%2Fmytest&client_id=ABCLA1YXME8Y4VQHLPBGHVXO2QRN59ZZ%40AMER.OAUTHAP

I'm getting this error: 
_A third-party application may be attempting to make unauthorized access to your account._

There was a similar issue posted here, but it included other stuff like how to get the consumerID etc... https://github.com/areed1192/td-ameritrade-python-api/issues/14  It never actually answered the reason for the error. 

I created developer account, set up app, and put in my consumer_id (aka Client_ID).

Should work without Python, but I originally ran a python program as in one of your videos (variables come from config.py) 
```
TDSession = TDClient(
    client_id=CONSUMER_KEY,
    redirect_uri=REDIRECT_URI,
    account_number=TD_ACCOUNT,
    credentials_path="./credpath"
```

It gave the URL above, but when I pasted it into browser, it gives me the erorr: 
_A third-party application may be attempting to make unauthorized access to your account._

Thanks,
Neal

**Comment by NealWalters** [comment]
Through trial and error, I found that http://localhost/mytest was the problem, just putting http://localhost worked fine.  Maybe you need to escape the / mark? 

Also, with PyCharm, when you paste a URL in the Run windows, it opens the URL in the browser and seems to be impossible to pass it back to the prompt.  However, taking off http:// at the beginning works.  So maybe you could also prompt for the url or just the key. 

Thanks for your hard work on this tool - look forwarding to doing fun stuff with this now. 

Neal

**Comment by areed1192** [comment]
Thanks for sharing this I'll look into the URL encoding. As for the PyCharm IDE, that particular platform tends to have very specific issues that don't appear to pop up in other editors. I've usually been pushing people to use the library in another IDE like Visual Studio Code.

**Comment by BrendanMartin** [comment]
To add to this, I had a similar problem. The URL generate for http://localhost was:
`https://auth.tdameritrade.com/auth/?response_type=code&amp;redirect_uri=http%3A%2F%2Flocalhost&amp;client_id=...`

And I received the same error as Neal.

But if I change it to just have raw slashes in the URL like this:
`https://auth.tdameritrade.com/auth?response_type=code&redirect_uri=http://localhost&client_id=...`

Then I am correctly presented with the login form to allow access.

**Comment by ehildebrandtrojo** [comment]
Something that worked for me is to always make sure to log off your Ameritrade developer account before pasting in the authentication URL generated by this API.

**Comment by codemasta1** [comment]
If anyone is having a similar issue, I got working by testing it in Postman first. Here is what worked:

https://auth.tdameritrade.com/auth?response_type=code&redirect_uri=http://127.0.01&client_id=YOURCONSUMERID%40AMER.OAUTHAP

**Comment by ConstantinosM** [comment]
For me, when I click on the link I get to the login page, I login then I get the authorization page, I select allow and then "Unable to connect An error occurred during a connection to localhost." Any information on how to try to find out what the error might be?

**Comment by ehildebrandtrojo** [comment]
> For me, when I click on the link I get to the login page, I login then I get the authorization page, I select allow and then "Unable to connect An error occurred during a connection to localhost." Any information on how to try to find out what the error might be?

Maybe you've already tried it, but make sure you're logged off on all browsers before you paste in your authentication url.
Also, I would try it with a brand new developer app. Sometimes if the authentication gets screwed up once, it never works again.

**Comment by ConstantinosM** [comment]
Thanks @ehildebrandtrojo for your response! I think I managed to make it work. I will need to check out again on Monday as I am off market hours and the script just exits without any error.
