### ISSUE TITLE
'//' in url whem making .get_transactions request

### ISSUE THREAD

**Issue by balvant813** [areed1192/td-ameritrade-python-api#85]
in client.py,  in def get_transactions :

`           # define the endpoint
            endpoint = "/accounts/{}/transactions".format(account)`

should it be ?:

`# define the endpoint
            endpoint = "accounts/{}/transactions".format(account)`

i.e. no "/" before "account"?
----------------------------------
in my code, when following request is made:

`symTrans = td_client.get_transactions(account=TD_ACCOUNT, transaction_type='ALL', start_date=dateFrm, end_date=dateTo)`

I am getting ERROR (I thinks b'cause of '...om/v1//accoun.....' in URL):

`BAD REQUEST - STATUS CODE: 401
RESPONSE URL: https://api.tdameritrade.com/v1//accounts/888888888/transactions?type=ALL&startDate=2020-08-04&endDate=2020-08-04
RESPONSE TEXT: 
          {
        "error":"The access token being passed has expired or is invalid."
      		}`

**Comment by areed1192** [comment]
This was fixed in the previous release, please upgrade the library to version `0.2.9`.
