### ISSUE TITLE
Getting the response message when there is an error 

### ISSUE THREAD

**Issue by NealWalters** [areed1192/td-ameritrade-python-api#86]
How can we catch error, i.e. get the error of the response message? 
My goal is to log successful and failed orders (with the error response) in a database. 

I have place_order working in general, but run across the error below. 

RESPONSE STATUS CODE: 400
RESPONSE URL: https://api.tdameritrade.com/v1/accounts/275152636/orders
RESPONSE HEADERS: {'Date': 'Tue, 04 Aug 2020 18:52:06 GMT', 'Content-Type': 'application/json', 'Content-Length': '89', 'Connection': 'keep-alive', 'X-API-Version': '1.11.5', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Cneonction': 'close', 'Access-Control-Allow-Origin': '', 'Access-Control-Allow-Headers': 'origin, x-requested-with, accept, authorization, content-type', 'Access-Control-Max-Age': '3628800', 'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE, OPTIONS, HEAD, PATCH', 'Content-Security-Policy': "frame-ancestors 'self'", 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains, max-age=31536000'}
RESPONSE PARAMS: {}
RESPONSE TEXT: {
  "error" : "Your buying power will be below zero ($3.14) if this order is accepted."

I tried a try as follows, but then the variable new_order_response was not available: 

try:
   new_order_response = td_client_session.place_order(account=config_user_dict['TD_ACCOUNT_NUM'], order=order_request)
except:
   pass

print ("line after call to TDAmeritrade")
pprint.pprint(new_order_response)

Error: NameError: name 'new_order_response' is not defined

**Comment by areed1192** [comment]
This was addressed in the new release, please update to version `0.2.9`.
