### ISSUE TITLE
Futures Chart History

### ISSUE THREAD

**Issue by bbhaught** [areed1192/td-ameritrade-python-api#89]
On the streaming API, when pulling the Futures Chart History the return JSON is not being parsed correctly.  

Key = Epoch
Chart Time = Open Price
Open Price = High Price
High Price = Low Price
Low Price = Close Price
Close Price = Volume

Also, when multiple symbols are put in, it only returns data for the first symbol.

**Comment by wuliwei9278** [comment]
What is the symbol you use for futures?

**Comment by ahmetsbilgin** [comment]
I can retrieve quotes for the futures using `TDSession.get_quotes`, however cannot get the historical data using neither `TDStreamingClient.chart_history_futures` nor `TDStreamingClient.chart`.

Anyone experiencing the same issue?
