### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by aharonp** [areed1192/td-ameritrade-python-api#9]
This client library looks like exactly what I need! However `pip install td-ameritrade-python-api` doesn't work for me.

```
ERROR: Could not find a version that satisfies the requirement td-ameritrade-python-api (from versions: none)
ERROR: No matching distribution found for td-ameritrade-python-api
```

It seems to be unavailable on PyPI.

**Comment by areed1192** [comment]
Hi there, it's not currently available on PyPi just yet. It will be uploaded later this weekend around Saturday.

**Comment by areed1192** [comment]
It should be available now.
