### ISSUE TITLE
Cash Equivalent order

### ISSUE THREAD

**Issue by eyesuk** [areed1192/td-ameritrade-python-api#94]
Hello Mr reed,
I am trying to place a cash equivalent order type but I am sure I am doing something wrong as I am getting the null error below:
```
"error" : "There must be at least one OrderItem component is null."
```

Looking at the code below, can you please advice as to what am I missing, I have been poking around for quite a bit and I can't figure it out of find an example that points me in the right direction.

```
new_order = Order()
new_order.order_type(order_type=ORDER_TYPE.MARKET)
new_order.order_session(session=ORDER_SESSION.NORMAL)
new_order.order_duration(duration=DURATION.DAY)
new_order.order_strategy_type(order_strategy_type=ORDER_STRATEGY_TYPE.SINGLE)

new_order_leg = OrderLeg()
new_order_leg.order_leg_instruction(instruction=ORDER_INSTRUCTIONS.BUY)
new_order_leg.order_leg_quantity(quantity=int(350.00))
new_order_leg.order_leg_asset(asset_type=ORDER_ASSET_TYPE.CASH_EQUIVALENT, symbol="YETI")
new_order_leg.order_leg_quantity_type(quantity_type=QUANTITY_TYPE.DOLLARS)
new_order.add_order_leg(order_leg=new_order_leg)
```
Thanks for your help

**Comment by areed1192** [comment]
I think it's because you have Asset Type as the following:

```python
new_order_leg.order_leg_asset(asset_type=ORDER_ASSET_TYPE.CASH_EQUIVALENT, symbol="YETI")
```

I think you want the Equity Asset type.

**Comment by eyesuk** [comment]
Sorry for the late reply,
I have changed this based on your suggestions and still no luck.  I feel this low priority so I'd understand if this falls all the way down the list.  Thanks for your help man

**Comment by eyesuk** [comment]
Does this mean this is no longer an issue?
