### ISSUE TITLE
difficulties with `TDClient.create_watchlist`

### ISSUE THREAD

**Issue by jkochNU** [areed1192/td-ameritrade-python-api#95]
I'm having some difficulties with the `create_watchlist` methods. According to the API, the method should actually POST, not PUT which might need to be changed in `client.py` line 1381.

Once I changed that, there is still a complaint in `_make_requests`.  Looks like the existence of 'Location' in the response is taken to be an indication that the request reflects an order, see line 553-555. However, in this case, that's not the right interpretation.

One last point: I remain uncertain whether the `watchlistItems` keyword argument of `create_watchlist` should be a list of `WatchlistItem` instances or a dictionary (of what)? The API asks for a list of json-type dicts, I think. For now I've done the cloogy thing of modifying the `create_watchlist_json` method to return a dict instead of a str and enter that into the list handed over to `create_watchlist`. 

[Awesome-awesome library, so grateful for it and all your time and generosity sharing it with the world.]

**Comment by eyesuk** [comment]
I was looking into this too and it appears that there body of the request gets passed in the incorrect format
When the request is sent, line 543, the body of the request is:
```
body:'name=wltest5&watchlistItems=quantity&watchlistItems=averagePrice&watchlistItems=commission&watchlistItems=purchasedDate&watchlistItems=instrument'
```

Even though the initial variable correctly formatted as below:
```
{
  "name": "wltest5",
  "watchlistItems": [
    {
      "quantity": 0,
      "averagePrice": 0,
      "commission": 0,
      "purchasedDate": "2020-08-29",
      "instrument": {
        "symbol": "AAPL",
        "assetType": "EQUITY"
      }
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/9576885/91646751-74580500-ea20-11ea-8cea-92dd3328e9fb.png)


I could be wrong though.

**Comment by carvey** [comment]
I second the observation made by @eyesuk. The body of the request is not a correctly parsed instance of watchlistItems. 

I'm going to poke around and see what's messing up the encoding. But perhaps a fix of the method type (put -> post) and better documentation on the expected format of watchlistItems could be good regardless of what the fix is.
