### ISSUE TITLE
Exception code not triggering in my bot

### ISSUE THREAD

**Issue by chipmaker** [areed1192/td-ameritrade-python-api#96]
Pardon me for asking. I am only a Python novice/intermediate level programmer. The following exception code in my program does not take effect and print the custom messages when TDClient crashes. I am running python on Windows machine.

`from td.client import TDClient`

Then in a class I have the following code.
  ```
  try:
            # Create a new exchange session
            self.exchange = TDClient(account_number=ACCOUNT_NUMBER, client_id=CONSUMER_ID, redirect_uri=REDIRECT_URI)
            # Login to the session
            self.exchange.login()
            logger.info(self.exchange)
  except AttributeError:
            logger.info('-' * 36, ' ERROR ', '-' * 35)
            logger.info('Exchange td not found. Please check the exchange is supported.')
            logger.info('-' * 80)
            quit()
```

**Comment by areed1192** [comment]
What are you expecting the script to do? Because right now, I don't see where it would fail to run if all the content you pass through is correct.

**Comment by chipmaker** [comment]
Yes. If the content is right, the script won't fail. Most common reason for program crash has been connection aborted. When I am running the api in a while loop from 6:30PM to 1:00PM, the program crash has been happening from time to time. If I got a message printed, then I could transfer the message via a function in except block to my Telegram messenger app. That way, I could get back and just rerun. I have two automated signal generators 'bnsig' and 'cbsig' here on github. I am trying something on similar lines with your api and having a crashinformer inside except block helps. If thereis a way to route all except blocks to a global variable/function, then any message in that except block could also be routed to that global variable/function which then sends that as a SMS/message on a messaging app.

**Comment by mandarl** [comment]
@chipmaker I think you want to catch all exceptions like this:
 ```
except: # catch *all* exceptions
   e = sys.exc_info()[0]
   write_to_page( "<p>Error: %s</p>" % e )
```
But if you are getting a lot of connection related issues then you should check if you are connected to the internet before doing anything else. This has some good ideas: https://stackoverflow.com/questions/3764291/checking-network-connection
