### ISSUE TITLE
There appears to be something wrong with the way 'credentials_file_exists' variable is assigned

### ISSUE THREAD

**Issue by chipmaker** [areed1192/td-ameritrade-python-api#97]
Pardon me, I'm only a novice/intermediate level Python programmer. There appears to be something wrong with 'credentials_file_exists' variable is assigned in _state_manager function of TDClient class.

I just hacked it adding the following code
        credentials_file_exists =os.path.isfile(credentials_file_path)

Don't know if I did it right, now I have issues with 'refresh_token'. Everytime, I am deleting td_state.json file and rerunning the authentication process.

**Comment by taewookim** [comment]
Also getting 
`FileNotFoundError: [Errno 2] No such file or directory: '/home/osboxes/tos/lib/python3.7/site-packages/td/td_state.json'
`

Full stack

`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-f7f69d14d27d> in <module>
      4 TDSession = TDClient(
      5     client_id='UR8DA3SAP4XSVEXMEOXPKJK1OKBTGIWA',
----> 6     redirect_uri='http://localhost/',
      7 #     credentials_path='<PATH_TO_CREDENTIALS_FILE>'
      8 )

~/tos/lib/python3.7/site-packages/td/client.py in __init__(self, client_id, redirect_uri, account_number, credentials_path, auth_flow, _do_init)
    131         # call the state_manager method and update the state to init (initalized)
    132         if _do_init:
--> 133             self._state_manager('init')
    134 
    135         # Initalize the client with no streaming session.

~/tos/lib/python3.7/site-packages/td/client.py in _state_manager(self, action)
    224         if action == 'init' and self.config['cache_state'] and credentials_file_exists:
    225 
--> 226             with open(file=credentials_file_path, mode='r') as json_file:
    227                 self.state.update(json.load(json_file))
    228 

FileNotFoundError: [Errno 2] No such file or directory: '/home/osboxes/tos/lib/python3.7/site-packages/td/td_state.json'
`

**Comment by areed1192** [comment]
Yes, it looks like it's a bug, right now in the `utils` file the order the file is checked is causing an issue because it checks if it exists before the actual file path is returned. I made note of the bug and will push it out in the next release. Thanks for bringing this to my attention.
