### ISSUE TITLE
How to initiate the authentication process without existing json file?

### ISSUE THREAD

**Issue by pmettler** [areed1192/td-ameritrade-python-api#98]
Hello together, I am relatively new with the API tool and now trying to get it run. I also already watched the videos but the code described in there are not anymore the same to the version 0.3.0.

Since I have no json file I need to create one with the procedure, that is clear. So I start with following code in 'test.py':

from Client import TDClient
import config2

td_session = TDClient(client_id=config2.CONSUMER_ID,redirect_uri=config2.REDIRECT_URI, account_number=config2.ACCOUNT_NUMBER, credentials_path="/Users/patrickmettler/Reed")
td_session.login()_

No I receive following message:
  File "/Users/patrickmettler/Reed/Client.py", line 183, in _state_manager
    with open(file=credentials_file_path, mode='r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/patrickmettler/Reed/td_state.json'

My init-method in class TDClient() (Client.py) looks looks as follows:   

def __init__(self, client_id: config2.CONSUMER_ID, redirect_uri: config2.REDIRECT_URI, account_number: config2.ACCOUNT_NUMBER, credentials_path: "/Users/patrickmettler/Reed", auth_flow: str = 'default', _do_init: bool = True) -> None:

I am totally confused since I've never referred to any json file called td_state.json. Why is the procedure looking for that? 

I already thank everybody who is willing and able to help me.

**Comment by eyesuk** [comment]
Can you please specify what are you trying to do?  I am bit confused.
Are you trying to send a trade? get quotes? what exactly?

**Comment by pmettler** [comment]
Thanks for your response. I am struggling with the authentication process. I copied all the files uploaded here and changed the Client.py with my data (account_number, etc.). I also created the path for the json file but without the file itself as it doesn't exist. 

In order to run the authentication I ran another py.file (called test.py) and imported the library  and the config file

**Comment by eyesuk** [comment]
When you say authentication process do you mean the initial authentication of your app to TDA?

**Comment by pmettler** [comment]
yes

**Comment by eyesuk** [comment]
You might want to wait a few and try it again, I am unable to log into tea this morning for some reason as it appears their site is down.  I also tried to submit an order without luck

**Comment by pmettler** [comment]
I can log in. I also was able to create a json file with the "old script" shown in the video. But since something else went wrong there I started to switch over to version 0.3.0. Now I want to create a new json file. I am working in another folder, no references are set

**Comment by eyesuk** [comment]
Unfortunately I am unable to log in via the web, ToS or the app. maybe is just where I am but the site seems to be unavailable

**Comment by pmettler** [comment]
I am sorry for that. Do you see already an issue with my code lines? I mean, I really only copied the original script and changed as described as follows:

def __init__(self, client_id: config2.CONSUMER_ID, redirect_uri: config2.REDIRECT_URI, account_number: config2.ACCOUNT_NUMBER, credentials_path: "/Users/patrickmettler/Reed", auth_flow: str = 'default', _do_init: bool = True) -> None:

The path exists, but no json file in

**Comment by eyesuk** [comment]
TBH, I have no idea what you are doing as I did not do any of that, I followed the instructions in the [Workflow Section](https://github.com/areed1192/td-ameritrade-python-api#authentication-workflow) and was able to get things working properly.

**Comment by pmettler** [comment]
I copied the files onto my computer, started Visual Studio Code and and ran a python file to use the Library

<img width="681" alt="image" src="https://user-images.githubusercontent.com/70354459/91660769-9a73b880-eaa5-11ea-8e46-f72b712ebbf4.png">

As the account and the folder is specified I chose the 2nd option step with all data. Instead of creating a json file what I expected I received a message that he cannot find it

**Comment by eyesuk** [comment]
did you install the python package? also can I see a screenshot of your VS code with this code?

**Comment by pmettler** [comment]
Yes, I installed the python package.

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/70354459/91660981-2afec880-eaa7-11ea-97f7-9a2a8fe8f73b.png">

**Comment by eyesuk** [comment]
I am sorry I meant the code you are running in VS code, that is the library code

**Comment by pmettler** [comment]
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/70354459/91661012-64cfcf00-eaa7-11ea-9430-58cac14380c8.png">

**Comment by eyesuk** [comment]
you are running the wrong code.
your code should look like this:
```
import  config
from td.client import TDClient

TDSession = TDClient(
    client_id=config.api_key,
    redirect_uri=config.redirect_uri,
    credentials_path= config.token_path
)

# Login to the session
TDSession.login()
```

**Comment by pmettler** [comment]
so I do exactly the same, I only named them slightly different

**Comment by pmettler** [comment]
I even wonder how yours can work since there is no account number in

**Comment by eyesuk** [comment]
you only need account number to perform account specific requests like orders.
If you are right, then from here all you need to do is perform the auth workflow steps

**Comment by pmettler** [comment]
I assume we have a misunderstand each other. The code gives me an error message 

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/70354459/91661278-0277ce00-eaa9-11ea-9e81-bcd67a4e30b8.png">

**Comment by pmettler** [comment]
Why is it looking for such a file?

**Comment by eyesuk** [comment]
If I was you, I would install a virtualenv and try installing it in an env specific for this package and try it again.

**Comment by pmettler** [comment]
I also tried that. No success

**Comment by eyesuk** [comment]
Paste your code here and I will try it

**Comment by pmettler** [comment]
The entire code here or do you rather want the python file?

**Comment by pmettler** [comment]
import os
import time
import json
import datetime
import pathlib
import requests
import urllib.parse
import config2

from typing import Any
from typing import Dict
from typing import List
from typing import Union
from typing import Optional

from utils import StatePath
from utils import TDUtilities

from enums import VALID_CHART_VALUES
from enums import ENDPOINT_ARGUMENTS

from oauth import run 
from oauth import shutdown
from auth import FlaskTDAuth

from exceptions import TknExpError
from exceptions import ExdLmtError
from exceptions import NotNulError
from exceptions import ForbidError
from exceptions import NotFndError
from exceptions import ServerError
from exceptions import GeneralError




class TDClient():   

    def __init__(self, client_id: config2.CONSUMER_ID, redirect_uri: config2.REDIRECT_URI, account_number: config2.ACCOUNT_NUMBER, credentials_path: config2.CREDENTIALS_PATH, auth_flow: str = 'default', _do_init: bool = True) -> None:

        # Define the configuration settings.
        self.config = {
            'cache_state': True,
            'api_endpoint': 'https://api.tdameritrade.com',
            'api_version': 'v1',
            'auth_endpoint': 'https://auth.tdameritrade.com/auth',
            'token_endpoint': 'oauth2/token',
            'refresh_enabled': True
        }

        # Define the initalized state, these are the default values.
        self.state = {
            'access_token': None,
            'refresh_token': None,
            'access_token_expires_at': 0,
            'refresh_token_expires_at': 0,
            'logged_in': False
        }

        self.auth_flow = auth_flow
        self.client_id = client_id
        self.redirect_uri = redirect_uri
        self.account_number = account_number
        self.credentials_path = StatePath(credentials_file=credentials_path)
        self._redirect_code = None
        self._td_utilities = TDUtilities()


        if self.auth_flow == 'flask':
            self._flask_app = FlaskTDAuth(
                client_id=self.client_id,
                redirect_uri=self.redirect_uri,
                credentials_file=self.credentials_path
            )
        else:
            self._flask_app = None
        
        # define a new attribute called 'authstate' and initialize to `False`. This will be used by our login function.
        self.authstate = False


        # call the state_manager method and update the state to init (initalized)
        if _do_init:
            self._state_manager('init')

        # Initalize the client with no streaming session.
        self.streaming_session = None





    def __repr__(self) -> str:

        # define the string representation
        str_representation = '<TDAmeritrade Client (logged_in={login_state}, authorized={auth_state})>'.format(login_state=self.state['logged_in'],auth_state=self.authstate)

        return str_representation






    def _headers(self, mode: str = None) -> dict:
        """Create the headers for a request.
        Returns a dictionary of default HTTP headers for calls to TD Ameritrade API,
        in the headers we defined the Authorization and access token.
        Arguments:
        ----
        mode {str} -- Defines the content-type for the headers dictionary. (default: {None})
        
        Returns:
        ----
        {dict} -- Dictionary with the Access token and content-type
            if specified
        """

        # create the headers dictionary
        headers = {
            'Authorization': 'Bearer {token}'.format(token = self.state['access_token'])
        }

        if mode == 'json':
            headers['Content-Type'] = 'application/json'
        elif mode == 'form':
            headers['Content-Type'] = 'application/x-www-form-urlencoded'

        return headers





    def _api_endpoint(self, endpoint: str, resource: str = None) -> str:
        """Convert relative endpoint (e.g., 'quotes') to full API endpoint.
        Arguments:
        ----
        endpoint {str} -- The URL that needs conversion to a full endpoint URL.
        resource {str} -- The API resource URL that you want to request. (default: {None})
        Returns:
        ----
        {str} -- A full url that specifies a valid endpoint.
        """

        # Define the parts.
        if resource:
            parts = [resource, self.config['api_version'], endpoint]
        else:
            parts = [self.config['api_endpoint'], self.config['api_version'], endpoint]

        # Built the URl
        return '/'.join(parts)




    def _state_manager(self, action: str) -> None:
        """Manages the session state.
        Manages the self.state dictionary. Initalize State will set
        the properties to their default value. Save will save the 
        current state if 'cache_state' is set to TRUE.
        Arguments:
        ----
        action {str}: action argument must of one of the following:
            'init' -- Initalize State.
            'save' -- Save the current state.
        """

        credentials_file = self.credentials_path
        credentials_file_exists = credentials_file.does_credentials_file_exist
        
        # If it's a directory, then create json setting path.
        if credentials_file.credentials_file.is_dir():
            credentials_file_path = credentials_file.json_library_path()
        else:
            credentials_file_path = credentials_file.credentials_file.absolute()

        # if they allow for caching and the file exists then load it.
        if action == 'init' and self.config['cache_state'] and credentials_file_exists:
            
            with open(file=credentials_file_path, mode='r') as json_file:
                self.state.update(json.load(json_file))

        # If they don't allow for caching and the file exists, then delete it.
        elif action == 'init' and self.config['cache_state'] == False and credentials_file_exists:
            credentials_file.unlink()

        # if they allow for caching and the file does not exists then use the default state.
        elif action == 'init' and self.config['cache_state'] and not credentials_file_exists:
            print('Their is no state file to load, will use default state.')

        # if they want to save it and have allowed for caching then load the file.
        elif action == 'save' and self.config['cache_state']:
            
            with open(file=credentials_file_path, mode='w+') as json_file:
                json.dump(obj=self.state, fp=json_file, indent=4)





    def login(self) -> bool:
        """Logs the user into the TD Ameritrade API.
        Ask the user to authenticate  themselves via the TD Ameritrade Authentication Portal. This will
        create a URL, display it for the User to go to and request that they paste the final URL into
        command window. Once the user is authenticated the API key is valide for 90 days, so refresh
        tokens may be used from this point, up to the 90 days.
        Returns:
        ----
        {bool} -- Specifies whether it was successful or not.
        """

        # if caching is enabled then attempt silent authentication.
        if self.config['cache_state'] and self._silent_sso():
            self.authstate = True
            return True
        
        if self._flask_app and self.auth_flow == 'flask':
            run(flask_client=self._flask_app, close_after=True)

        else:

            # prepare the payload to login
            data = {
                'response_type': 'code',
                'redirect_uri': self.redirect_uri,
                'client_id': self.client_id + '@AMER.OAUTHAP'
            }

            # url encode the data.
            params = urllib.parse.urlencode(data)

            # build the full URL for the authentication endpoint.
            url = self.config['auth_endpoint'] + "/?" + params

            # aks the user to go to the URL provided, they will be prompted to authenticate themsevles.
            print('Please go to URL provided authorize your account: {}'.format(url))

            # ask the user to take the final URL after authentication and paste here so we can parse.
            my_response = input('Paste the full URL redirect here: ')

            # store the redirect URL
            self._redirect_code = my_response

            # this will complete the final part of the authentication process.
            self.grab_access_token()

        self.authstate = True

        return True



    def logout(self) -> None:
        """Clears the current TD Ameritrade Connection state."""

        # change state to initalized so they will have to either get a
        # new access token or refresh token next time they use the API
        self._state_manager('init')




    def grab_access_token(self) -> bool:
        """Access token handler for AuthCode Workflow.
        
        This takes the authorization code parsed from
        the auth endpoint to call the token endpoint
        and obtain an access token.
        Returns:
        ----
        {bool} -- `True` if successful, `False` otherwise.
        """

        # Parse the URL
        url_dict = urllib.parse.parse_qs(self._redirect_code)

        # Grab the Code.
        url_code = list(url_dict.values())[0][0]

        # Define the parameters of our access token post.
        data = {
            'grant_type': 'authorization_code',
            'client_id': self.client_id + '@AMER.OAUTHAP',
            'access_type': 'offline',
            'code': url_code,
            'redirect_uri': self.redirect_uri
        }

        token_response = self._make_request(
            method='post',
            endpoint=self.config['token_endpoint'],
            mode='form',
            data=data
        )

        self._token_save(token_response)
        return True





    def grab_refresh_token(self) -> bool:
        """Refreshes the current access token.
        
        This takes a  valid refresh token and refreshes
        an expired access token.
        Returns:
        ----
        {bool} -- `True` if successful, `False` otherwise.
        """

        # build the parameters of our request
        data = {
            'client_id': self.client_id,
            'grant_type': 'refresh_token',
            'access_type': 'offline',
            'refresh_token': self.state['refresh_token']
        }

        token_response = self._make_request(
            method='post',
            endpoint=self.config['token_endpoint'],
            mode='form',
            data=data
        )

        self._token_save(token_response)
        
        return True



    def _silent_sso(self) -> bool:
        """
        Attempt a silent authentication, by checking whether current access token
        is valid and/or attempting to refresh it. Returns True if we have successfully 
        stored a valid access token.
        Returns:
        ----
        {bool} -- Specifies whether it was successful or not.
        """

        # if the current access token is not expired then we are still authenticated.
        if self._token_seconds(token_type='access_token') > 0:
            return True

        # if the refresh token is expired then you have to do a full login.
        elif self._token_seconds(token_type='refresh_token') <= 0:
            return False

        # if the current access token is expired then try and refresh access token.
        elif self.state['refresh_token'] and self.grab_refresh_token():
            return True

        # More than likely a first time login, so can't do silent authenticaiton.
        return False


    def _token_save(self, token_dict: dict) -> dict:
        """Parses the token and saves it.
        
        Parses an access token from the response of a POST request and saves it
        in the state dictionary for future use. Additionally, it will store the
        expiration time and the refresh token.
        Arguments:
        ----
        token_dict {dict} -- A response object recieved from the `grab_refresh_token` or
            `grab_access_token` methods.
        
        Returns:
        ----
        {dict} -- A token dictionary with the new added values.
        """

        # make sure there is an access token before proceeding.
        if 'access_token' not in token_dict:
            self.logout()
            return False

        # save the access token and refresh token
        self.state['access_token'] = token_dict['access_token']
        self.state['refresh_token'] = token_dict['refresh_token']

        # store token expiration time
        access_token_expire = time.time() + int(token_dict['expires_in'])
        refresh_token_expire = time.time() + int(token_dict['refresh_token_expires_in'])
        self.state['access_token_expires_at'] = access_token_expire
        self.state['refresh_token_expires_at'] = refresh_token_expire
        self.state['access_token_expires_at_date'] = datetime.datetime.fromtimestamp(access_token_expire).isoformat()
        self.state['refresh_token_expires_at_date'] = datetime.datetime.fromtimestamp(refresh_token_expire).isoformat()
        self.state['logged_in'] = True

        self._state_manager('save')

        return self.state


    def _token_seconds(self, token_type: str = 'access_token') -> int:
        """Determines time till expiration for a token.
        
        Return the number of seconds until the current access token or refresh token
        will expire. The default value is access token because this is the most commonly used
        token during requests.
        Arguments:
        ----
        token_type {str} --  The type of token you would like to determine lifespan for. 
            Possible values are ['access_token', 'refresh_token'] (default: {access_token})
        
        Returns:
        ----
        {int} -- The number of seconds till expiration.
        """

        # if needed check the access token.
        if token_type == 'access_token':

            # if the time to expiration is less than or equal to 0, return 0.
            if not self.state['access_token'] or time.time() + 60 >= self.state['access_token_expires_at']:
                return 0

            # else return the number of seconds until expiration.
            token_exp = int(self.state['access_token_expires_at'] - time.time() - 60)

        # if needed check the refresh token.
        elif token_type == 'refresh_token':

            # if the time to expiration is less than or equal to 0, return 0.
            if not self.state['refresh_token'] or time.time() + 60 >= self.state['refresh_token_expires_at']:
                return 0

            # else return the number of seconds until expiration.
            token_exp = int(self.state['refresh_token_expires_at'] - time.time() - 60)

        return token_exp


    def _token_validation(self, nseconds: int = 60):
        """Checks if a token is valid.
        Verify the current access token is valid for at least N seconds, and
        if not then attempt to refresh it. Can be used to assure a valid token
        before making a call to the TD Ameritrade API.
        Arguments:
        ----
        nseconds {int} -- The minimum number of seconds the token has to be 
            valid for before attempting to get a refresh token. (default: {5})
        """

        if self._token_seconds(token_type='access_token') < nseconds and self.config['refresh_enabled']:
            self.grab_refresh_token()






    def _make_request(self, method: str, endpoint: str, mode: str = None, params: dict = None, data: dict = None, json:dict = None, 
                        order_details: bool = False) -> Any:
        """Handles all the requests in the library.
        A central function used to handle all the requests made in the library,
        this function handles building the URL, defining Content-Type, passing
        through payloads, and handling any errors that may arise during the request.
        Arguments:
        ----
        method: The Request method, can be one of the
            following: ['get','post','put','delete','patch']
        
        endpoint: The API URL endpoint, example is 'quotes'
        mode: The content-type mode, can be one of the
            following: ['form','json']
        
        params: The URL params for the request.
        
        data: A data payload for a request.
        json: A json data payload for a request
        Returns:
        ----
        A Dictionary object containing the JSON values.            
        """

        url = self._api_endpoint(endpoint=endpoint)
        headers = self._headers(mode=mode)

        # Make sure the token is valid if it's not a Token API call.
        if endpoint != self.config['token_endpoint']:
            self._token_validation()
        elif endpoint == self.config['token_endpoint']:
            del headers['Authorization']

        # Define a new session.
        request_session = requests.Session()
        request_session.verify = True

        # Define a new request.
        request_request = requests.Request(
            method=method.upper(),
            headers=headers,
            url=url,
            params=params,
            data=data,
            json=json
        ).prepare()
        
        # Send the request.
        response: requests.Response = request_session.send(request=request_request)

        request_session.close()

        # grab the status code
        status_code = response.status_code

        # grab the response headers.
        response_headers = response.headers

        # Grab the order id, if it exists.
        if 'Location' in response_headers:
            order_id = response_headers['Location'].split('orders/')[1]
        else:
            order_id = ''

        # If it's okay and we need details, then add them.
        if response.ok and order_details:
            response_dict = {
                'order_id':order_id,
                'headers':response_headers,
                'content':response.content,
                'status_code':status_code,
                'request_body':response.request.body,
                'request_method':response.request.method
            }

            return response_dict

        # If it's okay and no details.
        elif response.ok:
            return response.json()

        else:

            if response.status_code == 400:
                raise NotNulError(message=response.text)
            elif response.status_code == 401:
                raise TknExpError(message=response.text)
            elif response.status_code == 403:
                raise ForbidError(message=response.text)
            elif response.status_code == 404:
                raise NotFndError(message=response.text)
            elif response.status_code == 429:
                raise ExdLmtError(message=response.text)
            elif response.status_code == 500 or response.status_code == 503:
                raise ServerError(message=response.text)
            elif response.status_code > 400:
                raise GeneralError(message=response.text)



    def _validate_arguments(self, endpoint: str, parameter_name: str, parameter_argument: List[str]) -> bool:
        """Validates arguments for an API call.
        This will validate an argument for the specified endpoint and raise an error if the argument
        is not valid. Can take both a list of arguments or a single argument.
        Arguments:
        ----
        endpoint {str} -- This is the endpoint name, and should line up 
            exactly with the TD Ameritrade Client library.
        parameter_name {str} -- An endpoint can have a parameter that needs 
            to be passed through, this represents the name 
            of that parameter.
        parameter_argument {List[str]} -- The arguments being validated for the 
            particular parameter name. This can either be a single value or a list 
            of values.
        Returns:
        ----
        {bool} --- If all arguments are valid then `True`, `False` if any are invalid.
        
        Raises:
        ----
        ValueError()
        Usage:
        ----
            >>> api_endpoint = 'get_market_hours'
            >>> para_name = 'markets'
            >>> para_args = ['FOREX', 'EQUITY']
            >>> self.validate_arguments(
                endpoint = api_endpoint, 
                parameter_name = para_name, 
                parameter_argument = para_args
            )
        """

        message = '\nThe argument is not valid, please choose a valid argument: {}\n'

        # Grab the parameters, and the possible arguments.
        parameters = ENDPOINT_ARGUMENTS[endpoint]
        arguments = parameters[parameter_name]

        if isinstance(parameter_argument,str):
            parameter_argument = [parameter_argument]

        # See if any of the arguments aren't in the possible values.
        validation_result = [argument in arguments for argument in parameter_argument]

        # if any of the results are FALSE then raise an error.
        if False in validation_result:
            raise ValueError(message.format(' ,'.join(arguments)))
        else:
            return True



#As of here the authentification is done and other endpoints are called

    def _prepare_arguments_list(self, parameter_list: List) -> str:
        """Preps an argument list for an API Call.
        Some endpoints can take multiple values for a parameter, this
        method takes that list and creates a valid string that can be 
        used in an API request. The list can have either one index or
        multiple indexes.
        Arguments:
        ----
        parameter_list: A list of paramater values 
            assigned to an argument.
        Usage:
        ----
            >>> td_client._prepare_arguments_list(parameter_list = ['MSFT', 'SQ'])
        """

        return ','.join(parameter_list)




    def get_quotes(self, instruments: List) -> Dict:
        """Grabs real-time quotes for an instrument.
        Serves as the mechanism to make a request to the Get Quote and Get Quotes Endpoint.
        If one item is provided a Get Quote request will be made and if more than one item
        is provided then a Get Quotes request will be made.
        Documentation:
        ----
        https://developer.tdameritrade.com/quotes/apis
        Arguments:
        ----
        instruments: A list of different financial instruments.
        Usage:
        ----
            >>> td_client.get_quotes(instruments=['MSFT'])
            >>> td_client.get_quotes(instruments=['MSFT','SQ'])
        """
        # because we have a list argument, prep it for the request.
        instruments = self._prepare_arguments_list(parameter_list=instruments)

        # build the params dictionary
        params = {
            'apikey': self.client_id,
            'symbol': instruments
        }

        # define the endpoint
        endpoint = 'marketdata/quotes'

        # return the response of the get request.
        return self._make_request(method='get', endpoint=endpoint, params=params)

**Comment by pmettler** [comment]
And thanks for all your support

**Comment by eyesuk** [comment]
I am looking for your code, the code you posted is the library code that we all use and we know works, as that is what I am using.  I am asking for the code you are using that leverages the Library

**Comment by pmettler** [comment]
from Client import TDClient
import config2

td_session = TDClient(client_id=config2.CONSUMER_ID,redirect_uri=config2.REDIRECT_URI,account_number=config2.ACCOUNT_NUMBER,credentials_path=config2.CREDENTIALS_PATH)

td_session.login()

**Comment by pmettler** [comment]
Ang again, maybe your variables have other names, but this cannot be the reason

**Comment by pmettler** [comment]
import time
import json
import pathlib
import config2

from configparser import ConfigParser
from requests_oauthlib import OAuth2Session
from datetime import datetime
from td.utils import StatePath

from typing import Union
from typing import List
from typing import Tuple


class FlaskTDAuth():

    def __init__(self, client_id: config2.CONSUMER_ID, redirect_uri: config2.REDIRECT_URI, credentials_file: pathlib.Path) -> None:
        
        self.client_id: str = client_id    
        self.client_id_auth: str = client_id + '@AMER.OAUTHAP'
        self.redirect_uri: str = redirect_uri
        self.credentials_file: StatePath = credentials_file
        self.authorization_base_url = 'https://auth.tdameritrade.com/auth'
        self.token_url = 'https://api.tdameritrade.com/v1/oauth2/token'        
        self.td_ouath_session: OAuth2Session = self._initate_oauth_workflow()


 
        
    def _initate_oauth_workflow(self):

        # Create a new OAuth Session.
        td_ameritrade = OAuth2Session(
            client_id=self.client_id_auth,
            redirect_uri=self.redirect_uri
        )

        return td_ameritrade




    def authorization_url(self) -> Tuple:

        # Create a new OAuth Session.
        authorization_url_ret, state = self.td_ouath_session.authorization_url(
            url=self.authorization_base_url,
            state=""
        )

        return (authorization_url_ret, state)




    def grab_access_token_and_refresh_token(self, url: str):
        
        # Grabs the token dict
        token_dict = self.td_ouath_session.fetch_token(
            token_url=self.token_url,
            access_type='offline',
            authorization_response=url,
            include_client_id=True
        )

        self.save_state(token_dict=token_dict)

        self.access_token_dict = token_dict

        return token_dict




    def grab_refresh_token(self):
        
        refresh_token_dict = self.td_ouath_session.refresh_token(
            token_url=self.token_url,
            client_id=self.client_id,
            access_type='offline',
            refresh_token=self.access_token_dict['refresh_token']
        )

        self.save_state(token_dict=refresh_token_dict)

        return refresh_token_dict



    def save_token(self, token_dict: dict) -> dict:
        
        # make sure there is an access token before proceeding.
        if 'access_token' not in token_dict:
            return False

        state = {}

        # save the access token and refresh token
        state['access_token'] = token_dict['access_token']
        state['refresh_token'] = token_dict['refresh_token']

        # store token expiration time
        access_token_expire = time.time() + int(token_dict['expires_in'])
        refresh_token_expire = time.time() + int(token_dict['refresh_token_expires_in'])
        state['access_token_expires_at'] = access_token_expire
        state['refresh_token_expires_at'] = refresh_token_expire
        state['access_token_expires_at_date'] = datetime.fromtimestamp(access_token_expire).isoformat()
        state['refresh_token_expires_at_date'] = datetime.fromtimestamp(refresh_token_expire).isoformat()
        state['logged_in'] = True
        
        return state

    def save_state(self, token_dict: dict) -> None:

        if self.credentials_file.exists():
            token_dict = self.save_token(token_dict=token_dict)
            credentials_file_path = self.credentials_file.get_file_path

            # if they want to save it and have allowed for caching then load the file.
            with open(credentials_file_path, 'w+') as json_file:
                json.dump(obj=token_dict, fp=json_file, indent=4)

**Comment by eyesuk** [comment]
Nothing in the library should be changed as everything is proven and it works.
As I mentioned, you should install the library in its own virtualenv, and follow all the instructions without changing anything anywhere and that will work as it worked for me.  after you have done that you can change the names or do whatever you want and see if there is something you are doing wrong.

**Comment by eyesuk** [comment]
You need to put this back they way it was
```
def __init__(self, client_id: config2.CONSUMER_ID, redirect_uri: config2.REDIRECT_URI, account_number: config2.ACCOUNT_NUMBER, credentials_path: config2.CREDENTIALS_PATH, auth_flow: str = 'default', _do_init: bool = True) 
```

I'd suggest you reinstall the library

**Comment by pmettler** [comment]
1. I re-installed both libraries:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/70354459/91670269-c57ffb80-eae9-11ea-89be-d1eae8332143.png">


2. I tried to run the setup.py but I get the following error:
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/70354459/91670229-75089e00-eae9-11ea-9d64-7329c0a242c4.png">

3. I only changed the the __init__ method in the client.py as follows:

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/70354459/91670321-53f47d00-eaea-11ea-9fd9-71fd126a1cfa.png">

4. I put my config2.py as well as my test.py in that td folder and ran my test.py in order to initiate the authorization process:

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/70354459/91670373-d5e4a600-eaea-11ea-8d88-768c17bad898.png">

....and now it is telling me again that the json file doesn't exist. Only difference, its looking in another folder (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/td/td_state.json')

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/70354459/91670983-899c6480-eaf0-11ea-9fa4-f363554716f7.png">

What is wrong here? Why does the code wants to open a json file which should be cerated in a very first step?

**Comment by pmettler** [comment]
I didn't remove any prefixes "td." in front of all the sub/libraries. Even that the config2.py is also inside the "td folder" I cannot referent to td.config2.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/70354459/91671082-75a53280-eaf1-11ea-9f17-521daa6081c0.png">

**Comment by eyesuk** [comment]
Bro, 
I am not sure why you trying to run setup.py or modifying any of the library.  if you want the library to work you need to follow the instructions, which it appears you are not doing.

**Comment by eyesuk** [comment]
Yo my bad, maybe you are new to this and I need to be more understanding, here is the list..

1. Once you run pip install, the library is installed and you don't have to do anything further
2. You need not to run any setup or modify any additional files as the code knows what to look for in the code you write.
3. All you need to do is use the sample code provided, and change the config.py to include your keys/parameters
4. if you follow everything in the intro page you should be good.

**Comment by pmettler** [comment]
Hello eyesuk,

thanks for all your help. After 12h in front of that stuff I will continue tomorrow.

I typed my data in directly (without config) and it put me through to my TDA account. Typical procedure followed, not further error message.

It seems that not only the folder is meant. It is more the folder + filename. Am I correct?

Hey and thanks. Fantastic job!!!!

**Comment by eyesuk** [comment]
I am glad you made some progress, I know what is like to be frustrated and stuck for hrs.  I am glad I could help.

**Comment by pmettler** [comment]
I am good to go from here. It works well, also with a config file.
