### ISSUE TITLE
Issue using with stream pipeline

### ISSUE THREAD

**Issue by seismars** [areed1192/td-ameritrade-python-api#99]
I'm trying to use the pipeline method for streaming market data. 
Sometimes my script runs fine. Sometimes my script run with error.
I have attached my script as well as the print out when successful or the error messages when went wrong.
https://gist.github.com/seismars/d750daf2b85e1663929fcbec91f1dfaa

Can someone please help take a look? Any suggestions on how should I address the issue?
Thanks,
Seismars

**Comment by areed1192** [comment]
I think it's because you're putting it in your own event loop so it might have a hard time trying to close everything correctly.

**Comment by seismars** [comment]
Alex,
I did lots of tests and also checked previous issues and pull requests. Later I followed the change suggested by pull request #87 and my issue solved. Please give it a look on pull request #87.
Thanks
